"""Core Policy Engine endpoint declarations for the authenticate app (§35).

Run ``python manage.py sync_policy_registry`` after editing this file, then
``python manage.py validate_policy_engine``.
"""

from typing import Any

_BASE: dict[str, Any] = {
    "app_key": "authenticate",
    "app_display_name": "Authenticate",
    "version": "1.0.0",
    "is_internal": False,
    "category_key": "authentication",
    "category_display_name": "Authentication",
}


def _dep(target_key: str, reason: str) -> dict[str, Any]:
    return {
        "target_permission_key": target_key,
        "direction": "forward",
        "dependency_type": "requires",
        "enforcement_mode": "strict",
        "reason": reason,
    }


_REQUIRES_LOGIN = [
    _dep("authenticate.session.login", "A session must be established by login before this endpoint is usable.")
]

# Account & session management endpoints use their own UI categories.
_ACCOUNT: dict[str, Any] = {
    "app_key": "authenticate",
    "app_display_name": "Authenticate",
    "version": "1.0.0",
    "is_internal": False,
    "category_key": "account_management",
    "category_display_name": "Account Management",
    "model_key": "user",
    "model_display_name": "User",
}
_SESSION_MGMT: dict[str, Any] = {
    "app_key": "authenticate",
    "app_display_name": "Authenticate",
    "version": "1.0.0",
    "is_internal": False,
    "category_key": "session_management",
    "category_display_name": "Session Management",
    "model_key": "session",
    "model_display_name": "Auth Session",
}

POLICY_ENDPOINTS: list[dict[str, Any]] = [
    # 1. Login — public entry point; establishes a device-bound session. Root dep.
    {
        **_BASE,
        "endpoint_key": "session-login",
        "permission_key": "authenticate.session.login",
        "model_key": "session",
        "model_display_name": "Auth Session",
        "operation_type": "custom",
        "display_name": "Login",
        "description": "Authenticate with username + password (+ device_id) and open a revocable session.",
        "http_method": "POST",
        "route_pattern": "/api/v1/auth/login/",
        "view_import_path": "authenticate.views.LoginView",
        "risk_level": "high",
        "is_dependency_root": True,
        "dependencies": [],
        "change_summary": "Initial registration of the login endpoint.",
        "change_reason": "authenticate app Phase 1 foundation.",
    },
    # 2. Refresh — rotate the session; requires an existing session (login).
    {
        **_BASE,
        "endpoint_key": "session-refresh",
        "permission_key": "authenticate.session.refresh",
        "model_key": "session",
        "model_display_name": "Auth Session",
        "operation_type": "custom",
        "display_name": "Refresh Session",
        "description": "Rotate the refresh session, issuing a new access + refresh credential.",
        "http_method": "POST",
        "route_pattern": "/api/v1/auth/refresh/",
        "view_import_path": "authenticate.views.RefreshView",
        "risk_level": "medium",
        "dependencies": _REQUIRES_LOGIN,
        "change_summary": "Initial registration of the refresh endpoint.",
        "change_reason": "authenticate app Phase 1 foundation.",
    },
    # 3. Logout — revoke the current session.
    {
        **_BASE,
        "endpoint_key": "session-logout",
        "permission_key": "authenticate.session.logout",
        "model_key": "session",
        "model_display_name": "Auth Session",
        "operation_type": "custom",
        "display_name": "Logout",
        "description": "Revoke the caller's current session (logout of this device).",
        "http_method": "POST",
        "route_pattern": "/api/v1/auth/logout/",
        "view_import_path": "authenticate.views.LogoutView",
        "risk_level": "low",
        "dependencies": _REQUIRES_LOGIN,
        "change_summary": "Initial registration of the logout endpoint.",
        "change_reason": "authenticate app Phase 1 foundation.",
    },
    # 4. Current user — read the authenticated user.
    {
        **_BASE,
        "endpoint_key": "user-me",
        "permission_key": "authenticate.user.me",
        "model_key": "user",
        "model_display_name": "User",
        "operation_type": "read",
        "display_name": "Current User",
        "description": "Return the currently authenticated user and forced-password-change state.",
        "http_method": "GET",
        "route_pattern": "/api/v1/auth/me/",
        "view_import_path": "authenticate.views.CurrentUserView",
        "risk_level": "low",
        "dependencies": _REQUIRES_LOGIN,
        "change_summary": "Initial registration of the current-user endpoint.",
        "change_reason": "authenticate app Phase 1 foundation.",
    },
    # 5. Change own password — clears must_change_password; revokes all sessions.
    {
        **_BASE,
        "endpoint_key": "user-change-password",
        "permission_key": "authenticate.user.change_password",
        "model_key": "user",
        "model_display_name": "User",
        "operation_type": "custom",
        "display_name": "Change Password",
        "description": "Change the caller's own password after confirming the current one.",
        "http_method": "POST",
        "route_pattern": "/api/v1/auth/password/change/",
        "view_import_path": "authenticate.views.PasswordChangeView",
        "risk_level": "high",
        "dependencies": _REQUIRES_LOGIN,
        "change_summary": "Initial registration of the change-password endpoint.",
        "change_reason": "authenticate app Phase 1 foundation.",
    },
    # 6. MFA enroll — begin TOTP enrollment.
    {
        **_BASE,
        "endpoint_key": "mfa-enroll",
        "permission_key": "authenticate.mfa.enroll",
        "model_key": "mfa",
        "model_display_name": "MFA Device",
        "operation_type": "custom",
        "display_name": "Begin MFA Enrollment",
        "description": "Create a pending TOTP device and return its secret + otpauth URL.",
        "http_method": "POST",
        "route_pattern": "/api/v1/auth/mfa/enroll/",
        "view_import_path": "authenticate.views.MfaEnrollView",
        "risk_level": "medium",
        "dependencies": _REQUIRES_LOGIN,
        "change_summary": "Initial registration of the MFA enroll endpoint.",
        "change_reason": "authenticate app Phase 2 (MFA).",
    },
    # 7. MFA verify — confirm/activate TOTP.
    {
        **_BASE,
        "endpoint_key": "mfa-verify",
        "permission_key": "authenticate.mfa.verify",
        "model_key": "mfa",
        "model_display_name": "MFA Device",
        "operation_type": "custom",
        "display_name": "Confirm MFA Enrollment",
        "description": "Confirm a pending TOTP enrollment with a current code, activating MFA.",
        "http_method": "POST",
        "route_pattern": "/api/v1/auth/mfa/verify/",
        "view_import_path": "authenticate.views.MfaVerifyView",
        "risk_level": "medium",
        "dependencies": [
            {
                "target_permission_key": "authenticate.mfa.enroll",
                "direction": "forward",
                "dependency_type": "requires",
                "enforcement_mode": "strict",
                "reason": "Enrollment must be started before it can be confirmed.",
            }
        ],
        "change_summary": "Initial registration of the MFA verify endpoint.",
        "change_reason": "authenticate app Phase 2 (MFA).",
    },
    # 8. MFA disable — turn off own MFA (not superadmin).
    {
        **_BASE,
        "endpoint_key": "mfa-disable",
        "permission_key": "authenticate.mfa.disable",
        "model_key": "mfa",
        "model_display_name": "MFA Device",
        "operation_type": "custom",
        "display_name": "Disable MFA",
        "description": "Disable the caller's own MFA after confirming password + a current code.",
        "http_method": "POST",
        "route_pattern": "/api/v1/auth/mfa/disable/",
        "view_import_path": "authenticate.views.MfaDisableView",
        "risk_level": "high",
        "dependencies": [
            {
                "target_permission_key": "authenticate.mfa.verify",
                "direction": "forward",
                "dependency_type": "requires",
                "enforcement_mode": "strict",
                "reason": "MFA must be enabled (enrolled and confirmed) before it can be disabled.",
            }
        ],
        "change_summary": "Initial registration of the MFA disable endpoint.",
        "change_reason": "authenticate app Phase 2 (MFA).",
    },
    # --- Phase 3: account management ---------------------------------------
    # 9. List accounts within the actor's managed tier.
    {
        **_ACCOUNT,
        "endpoint_key": "user-list",
        "permission_key": "authenticate.user.list",
        "operation_type": "list",
        "display_name": "List Accounts",
        "description": "List accounts within the caller's managed authority tier.",
        "http_method": "GET",
        "route_pattern": "/api/v1/auth/users/",
        "view_import_path": "authenticate.views.AccountListCreateView",
        "risk_level": "low",
        "dependencies": _REQUIRES_LOGIN,
        "change_summary": "Initial registration of the account list endpoint.",
        "change_reason": "authenticate app Phase 3 (account management).",
    },
    # 10. Create a subordinate account.
    {
        **_ACCOUNT,
        "endpoint_key": "user-create",
        "permission_key": "authenticate.user.create",
        "operation_type": "create",
        "display_name": "Create Account",
        "description": "Create a subordinate account (superadmin→admin, admin→lead manager).",
        "http_method": "POST",
        "route_pattern": "/api/v1/auth/users/",
        "view_import_path": "authenticate.views.AccountListCreateView",
        "risk_level": "high",
        "dependencies": [_dep("authenticate.user.list", "Managing accounts requires the ability to list them.")],
        "change_summary": "Initial registration of the account create endpoint.",
        "change_reason": "authenticate app Phase 3 (account management).",
    },
    # 11. Read a managed account.
    {
        **_ACCOUNT,
        "endpoint_key": "user-read",
        "permission_key": "authenticate.user.read",
        "operation_type": "read",
        "display_name": "View Account",
        "description": "Retrieve a single managed account.",
        "http_method": "GET",
        "route_pattern": "/api/v1/auth/users/<user_id>/",
        "view_import_path": "authenticate.views.AccountDetailView",
        "risk_level": "low",
        "dependencies": [_dep("authenticate.user.list", "Reading an account requires list access to its tier.")],
        "change_summary": "Initial registration of the account read endpoint.",
        "change_reason": "authenticate app Phase 3 (account management).",
    },
    # 12. Update a managed account's profile.
    {
        **_ACCOUNT,
        "endpoint_key": "user-update",
        "permission_key": "authenticate.user.update",
        "operation_type": "update",
        "display_name": "Edit Account",
        "description": "Edit permitted profile fields of a managed account.",
        "http_method": "PATCH",
        "route_pattern": "/api/v1/auth/users/<user_id>/",
        "view_import_path": "authenticate.views.AccountDetailView",
        "risk_level": "medium",
        "dependencies": [_dep("authenticate.user.read", "Editing requires read access to the account.")],
        "change_summary": "Initial registration of the account update endpoint.",
        "change_reason": "authenticate app Phase 3 (account management).",
    },
    # 13. Block a managed account.
    {
        **_ACCOUNT,
        "endpoint_key": "user-block",
        "permission_key": "authenticate.user.block",
        "operation_type": "custom",
        "display_name": "Block Account",
        "description": "Deactivate a managed account and revoke its sessions.",
        "http_method": "POST",
        "route_pattern": "/api/v1/auth/users/<user_id>/block/",
        "view_import_path": "authenticate.views.AccountBlockView",
        "risk_level": "high",
        "dependencies": [_dep("authenticate.user.read", "Blocking requires read access to the account.")],
        "change_summary": "Initial registration of the account block endpoint.",
        "change_reason": "authenticate app Phase 3 (account management).",
    },
    # 14. Restore a blocked account.
    {
        **_ACCOUNT,
        "endpoint_key": "user-restore",
        "permission_key": "authenticate.user.restore",
        "operation_type": "custom",
        "display_name": "Restore Account",
        "description": "Reactivate a blocked managed account.",
        "http_method": "POST",
        "route_pattern": "/api/v1/auth/users/<user_id>/restore/",
        "view_import_path": "authenticate.views.AccountRestoreView",
        "risk_level": "medium",
        "dependencies": [_dep("authenticate.user.read", "Restoring requires read access to the account.")],
        "change_summary": "Initial registration of the account restore endpoint.",
        "change_reason": "authenticate app Phase 3 (account management).",
    },
    # 15. Administratively reset a managed account's password.
    {
        **_ACCOUNT,
        "endpoint_key": "user-reset-password",
        "permission_key": "authenticate.user.reset_password",
        "operation_type": "custom",
        "display_name": "Reset Account Password",
        "description": "Set a temporary password on a managed account and revoke its sessions.",
        "http_method": "POST",
        "route_pattern": "/api/v1/auth/users/<user_id>/reset-password/",
        "view_import_path": "authenticate.views.AccountResetPasswordView",
        "risk_level": "high",
        "dependencies": [_dep("authenticate.user.read", "Resetting a password requires read access to the account.")],
        "change_summary": "Initial registration of the account password-reset endpoint.",
        "change_reason": "authenticate app Phase 3 (account management).",
    },
    # 16. Administratively reset a managed account's MFA.
    {
        **_ACCOUNT,
        "endpoint_key": "user-reset-mfa",
        "permission_key": "authenticate.user.reset_mfa",
        "operation_type": "custom",
        "display_name": "Reset Account MFA",
        "description": "Remove a managed account's MFA device and revoke its sessions.",
        "http_method": "POST",
        "route_pattern": "/api/v1/auth/users/<user_id>/reset-mfa/",
        "view_import_path": "authenticate.views.AccountResetMfaView",
        "risk_level": "high",
        "dependencies": [_dep("authenticate.user.read", "Resetting MFA requires read access to the account.")],
        "change_summary": "Initial registration of the account MFA-reset endpoint.",
        "change_reason": "authenticate app Phase 3 (account management).",
    },
    # 17. List a managed account's sessions.
    {
        **_ACCOUNT,
        "endpoint_key": "user-session-list",
        "permission_key": "authenticate.user.list_sessions",
        "operation_type": "list",
        "display_name": "List Account Sessions",
        "description": "List a managed account's active sessions.",
        "http_method": "GET",
        "route_pattern": "/api/v1/auth/users/<user_id>/sessions/",
        "view_import_path": "authenticate.views.AccountSessionListView",
        "risk_level": "low",
        "dependencies": [_dep("authenticate.user.read", "Viewing sessions requires read access to the account.")],
        "change_summary": "Initial registration of the account session-list endpoint.",
        "change_reason": "authenticate app Phase 3 (account management).",
    },
    # 18. Revoke a managed account's sessions.
    {
        **_ACCOUNT,
        "endpoint_key": "user-session-revoke",
        "permission_key": "authenticate.user.revoke_sessions",
        "operation_type": "custom",
        "display_name": "Revoke Account Sessions",
        "description": "Revoke one or all active sessions of a managed account.",
        "http_method": "POST",
        "route_pattern": "/api/v1/auth/users/<user_id>/sessions/revoke/",
        "view_import_path": "authenticate.views.AccountSessionRevokeView",
        "risk_level": "high",
        "dependencies": [
            _dep("authenticate.user.list_sessions", "Revoking requires the ability to list the account's sessions.")
        ],
        "change_summary": "Initial registration of the account session-revoke endpoint.",
        "change_reason": "authenticate app Phase 3 (account management).",
    },
    # 19. Review a managed account's authentication activity.
    {
        **_ACCOUNT,
        "endpoint_key": "user-events",
        "permission_key": "authenticate.user.list_events",
        "operation_type": "list",
        "display_name": "Review Account Auth Activity",
        "description": "List authentication audit events for a managed account.",
        "http_method": "GET",
        "route_pattern": "/api/v1/auth/users/<user_id>/events/",
        "view_import_path": "authenticate.views.AccountEventsView",
        "risk_level": "low",
        "dependencies": [_dep("authenticate.user.read", "Reviewing activity requires read access to the account.")],
        "change_summary": "Initial registration of the account auth-activity endpoint.",
        "change_reason": "authenticate app Phase 3 (account management + folded audit review).",
    },
    # --- Phase 3: own session management -----------------------------------
    # 20. List own sessions.
    {
        **_SESSION_MGMT,
        "endpoint_key": "session-list",
        "permission_key": "authenticate.session.list",
        "operation_type": "list",
        "display_name": "List Own Sessions",
        "description": "List the caller's own active sessions.",
        "http_method": "GET",
        "route_pattern": "/api/v1/auth/sessions/",
        "view_import_path": "authenticate.views.OwnSessionListView",
        "risk_level": "low",
        "dependencies": _REQUIRES_LOGIN,
        "change_summary": "Initial registration of the own-session list endpoint.",
        "change_reason": "authenticate app Phase 3 (session management).",
    },
    # 21. Revoke own sessions.
    {
        **_SESSION_MGMT,
        "endpoint_key": "session-revoke",
        "permission_key": "authenticate.session.revoke",
        "operation_type": "custom",
        "display_name": "Revoke Own Sessions",
        "description": "Revoke one, all-but-current, or all of the caller's own sessions.",
        "http_method": "POST",
        "route_pattern": "/api/v1/auth/sessions/revoke/",
        "view_import_path": "authenticate.views.OwnSessionRevokeView",
        "risk_level": "medium",
        "dependencies": [
            _dep("authenticate.session.list", "Revoking own sessions requires the ability to list them.")
        ],
        "change_summary": "Initial registration of the own-session revoke endpoint.",
        "change_reason": "authenticate app Phase 3 (session management).",
    },
]
