# Generated by Django 5.1.9 on 2026-07-23 10:23

import uuid

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # This app declares pg_trgm itself rather than relying on the leads
        # migration that also creates it. leads/0002 depends only on leads/0001,
        # so nothing orders it before this migration — on a fresh database the
        # gin_trgm_ops opclass could be missing when the indexes below are
        # built. Declaring it here is safe: Django's CreateExtension guards with
        # both an existence check and CREATE EXTENSION IF NOT EXISTS, so a
        # repeat is a no-op. A cross-app migration dependency was rejected
        # deliberately — applicants must not depend on leads (see models.py).
        TrigramExtension(),
        migrations.CreateModel(
            name="Applicant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name_np", models.CharField(max_length=255)),
                ("full_name_en", models.CharField(blank=True, max_length=255)),
                ("full_name_romanized", models.CharField(blank=True, max_length=255)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("undisclosed", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nationality", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("dormant", "Dormant"), ("archived", "Archived")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "creation_source",
                    models.CharField(
                        choices=[("lead_conversion", "Lead Conversion"), ("direct_admin", "Direct Admin Creation")],
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The Admin who created this applicant, by conversion or directly.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applicants_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Applicant",
                "verbose_name_plural": "Applicants",
                "db_table": "applicants_applicant",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicantAddress",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address_type",
                    models.CharField(choices=[("permanent", "Permanent"), ("current", "Current")], max_length=20),
                ),
                ("country", models.CharField(blank=True, max_length=100)),
                ("province", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("municipality", models.CharField(blank=True, max_length=150)),
                ("ward", models.CharField(blank=True, max_length=10)),
                ("street_address", models.CharField(blank=True, max_length=255)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="applicants.applicant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Applicant Address",
                "verbose_name_plural": "Applicant Addresses",
                "db_table": "applicants_applicantaddress",
                "ordering": ["address_type"],
            },
        ),
        migrations.CreateModel(
            name="ApplicantContactNumber",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_contact_number",
                                message="Contact number may contain digits, spaces, and + - ( ) only.",
                                regex="^\\+?[0-9][0-9 ()\\-]{4,31}$",
                            )
                        ],
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("home", "Home"),
                            ("work", "Work"),
                            ("whatsapp", "WhatsApp"),
                            ("viber", "Viber"),
                            ("other", "Other"),
                        ],
                        default="mobile",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_numbers",
                        to="applicants.applicant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Applicant Contact Number",
                "verbose_name_plural": "Applicant Contact Numbers",
                "db_table": "applicants_applicantcontactnumber",
                "ordering": ["-is_primary", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name_np", models.CharField(max_length=255)),
                ("full_name_en", models.CharField(blank=True, max_length=255)),
                ("relationship", models.CharField(blank=True, max_length=100)),
                (
                    "contact_number",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_contact_number",
                                message="Contact number may contain digits, spaces, and + - ( ) only.",
                                regex="^\\+?[0-9][0-9 ()\\-]{4,31}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="applicants.applicant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency Contact",
                "verbose_name_plural": "Emergency Contacts",
                "db_table": "applicants_emergencycontact",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("spouse", "Spouse"),
                            ("sibling", "Sibling"),
                            ("child", "Child"),
                            ("guardian", "Guardian"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("full_name_np", models.CharField(max_length=255)),
                ("full_name_en", models.CharField(blank=True, max_length=255)),
                ("occupation", models.CharField(blank=True, max_length=150)),
                (
                    "contact_number",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_contact_number",
                                message="Contact number may contain digits, spaces, and + - ( ) only.",
                                regex="^\\+?[0-9][0-9 ()\\-]{4,31}$",
                            )
                        ],
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_members",
                        to="applicants.applicant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Family Member",
                "verbose_name_plural": "Family Members",
                "db_table": "applicants_familymember",
                "ordering": ["relationship", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PassportDetail",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("passport_number", models.CharField(max_length=50)),
                ("issuing_country", models.CharField(blank=True, max_length=100)),
                ("place_of_issue", models.CharField(blank=True, max_length=150)),
                ("issued_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "applicant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="passport", to="applicants.applicant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Passport Detail",
                "verbose_name_plural": "Passport Details",
                "db_table": "applicants_passportdetail",
            },
        ),
        migrations.AddIndex(
            model_name="applicant",
            index=models.Index(fields=["status", "-created_at"], name="applicant_status_recent_idx"),
        ),
        migrations.AddIndex(
            model_name="applicant",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["full_name_np"], name="appl_name_np_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="applicant",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["full_name_en"], name="appl_name_en_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="applicant",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["full_name_romanized"], name="appl_name_rom_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddConstraint(
            model_name="applicantaddress",
            constraint=models.UniqueConstraint(
                fields=("applicant", "address_type"), name="uniq_applicant_address_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="applicantcontactnumber",
            constraint=models.UniqueConstraint(fields=("applicant", "number"), name="uniq_applicant_contact_number"),
        ),
    ]
