# Generated by Django 5.1.9 on 2026-07-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicants", "0003_english_only_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencycontact",
            name="full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="familymember",
            name="full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
