"""Core Policy Engine endpoint declarations for the institutions app (§35).

Run ``python manage.py sync_policy_registry`` after editing this file, then
``python manage.py validate_policy_engine``.

Unlike ``applicant_journeys``, ``_BASE`` here carries no ``model_key`` — this
app owns five models, so each entry names its own.

The dependency edges encode the catalogue's real build order: a program needs
a field and an institution, an institution needs a country, a campus needs an
institution. A client that has only ``program.create`` cannot in fact create
anything.
"""

from typing import Any

_BASE: dict[str, Any] = {
    "app_key": "institutions",
    "app_display_name": "Institutions",
    "version": "1.0.0",
    "is_internal": False,
    "category_key": "catalogue_management",
    "category_display_name": "Catalogue Management",
}


def _dep(target_key: str, reason: str) -> dict[str, Any]:
    return {
        "target_permission_key": target_key,
        "direction": "forward",
        "dependency_type": "requires",
        "enforcement_mode": "strict",
        "reason": reason,
    }


_LOGIN = _dep(
    "authenticate.session.login",
    "A session must be established by login before this endpoint is usable.",
)

_PHASE = "institutions app initial build — Phase 1 catalogue spine."


POLICY_ENDPOINTS: list[dict[str, Any]] = [
    # --- Field: the study-area reference table ----------------------------
    {
        **_BASE,
        "model_key": "field",
        "model_display_name": "Study Field",
        "endpoint_key": "catalogue-field-list",
        "permission_key": "institutions.field.list",
        "operation_type": "list",
        "display_name": "List Study Fields",
        "description": "List the study-area classifications used to group and search programs.",
        "http_method": "GET",
        "route_pattern": "/api/v1/catalogue/fields/",
        "view_import_path": "institutions.views.FieldListCreateView",
        "risk_level": "low",
        "dependencies": [_LOGIN],
        "change_summary": "Initial registration of the study-field list endpoint.",
        "change_reason": _PHASE,
    },
    {
        **_BASE,
        "model_key": "field",
        "model_display_name": "Study Field",
        "endpoint_key": "catalogue-field-create",
        "permission_key": "institutions.field.create",
        "operation_type": "create",
        "display_name": "Create Study Field",
        "description": "Add a study-area classification. Admin only.",
        "http_method": "POST",
        "route_pattern": "/api/v1/catalogue/fields/",
        "view_import_path": "institutions.views.FieldListCreateView",
        "risk_level": "medium",
        "dependencies": [_dep("institutions.field.list", "Creating fields requires the ability to list them.")],
        "change_summary": "Initial registration of the study-field create endpoint.",
        "change_reason": _PHASE,
    },
    {
        **_BASE,
        "model_key": "field",
        "model_display_name": "Study Field",
        "endpoint_key": "catalogue-field-read",
        "permission_key": "institutions.field.read",
        "operation_type": "read",
        "display_name": "View Study Field",
        "description": "Retrieve one study-area classification.",
        "http_method": "GET",
        "route_pattern": "/api/v1/catalogue/fields/<field_id>/",
        "view_import_path": "institutions.views.FieldDetailView",
        "risk_level": "low",
        "dependencies": [_dep("institutions.field.list", "Reading a field requires list access.")],
        "change_summary": "Initial registration of the study-field read endpoint.",
        "change_reason": _PHASE,
    },
    {
        **_BASE,
        "model_key": "field",
        "model_display_name": "Study Field",
        "endpoint_key": "catalogue-field-update",
        "permission_key": "institutions.field.update",
        "operation_type": "update",
        "display_name": "Edit Study Field",
        "description": "Correct a study field's name, ordering, or active flag. The code is immutable.",
        "http_method": "PATCH",
        "route_pattern": "/api/v1/catalogue/fields/<field_id>/",
        "view_import_path": "institutions.views.FieldDetailView",
        "risk_level": "medium",
        "dependencies": [_dep("institutions.field.read", "The field must be readable before it can be edited.")],
        "change_summary": "Initial registration of the study-field update endpoint.",
        "change_reason": _PHASE,
    },
    # --- Country ----------------------------------------------------------
    {
        **_BASE,
        "model_key": "country",
        "model_display_name": "Country",
        "endpoint_key": "catalogue-country-list",
        "permission_key": "institutions.country.list",
        "operation_type": "list",
        "display_name": "List Countries",
        "description": "List destination countries with their availability.",
        "http_method": "GET",
        "route_pattern": "/api/v1/catalogue/countries/",
        "view_import_path": "institutions.views.CountryListCreateView",
        "risk_level": "low",
        "dependencies": [_LOGIN],
        "change_summary": "Initial registration of the country list endpoint.",
        "change_reason": _PHASE,
    },
    {
        **_BASE,
        "model_key": "country",
        "model_display_name": "Country",
        "endpoint_key": "catalogue-country-create",
        "permission_key": "institutions.country.create",
        "operation_type": "create",
        "display_name": "Create Country",
        "description": "Add a destination country. Admin only.",
        "http_method": "POST",
        "route_pattern": "/api/v1/catalogue/countries/",
        "view_import_path": "institutions.views.CountryListCreateView",
        "risk_level": "medium",
        "dependencies": [_dep("institutions.country.list", "Creating countries requires the ability to list them.")],
        "change_summary": "Initial registration of the country create endpoint.",
        "change_reason": _PHASE,
    },
    {
        **_BASE,
        "model_key": "country",
        "model_display_name": "Country",
        "endpoint_key": "catalogue-country-read",
        "permission_key": "institutions.country.read",
        "operation_type": "read",
        "display_name": "View Country",
        "description": "Retrieve one country with its availability and counselling notes.",
        "http_method": "GET",
        "route_pattern": "/api/v1/catalogue/countries/<country_id>/",
        "view_import_path": "institutions.views.CountryDetailView",
        "risk_level": "low",
        "dependencies": [_dep("institutions.country.list", "Reading a country requires list access.")],
        "change_summary": "Initial registration of the country read endpoint.",
        "change_reason": _PHASE,
    },
    {
        **_BASE,
        "model_key": "country",
        "model_display_name": "Country",
        "endpoint_key": "catalogue-country-update",
        "permission_key": "institutions.country.update",
        "operation_type": "update",
        "display_name": "Edit Country",
        "description": (
            "Correct a country's name, notes, or availability. Setting a non-active status requires a note. "
            "The code is immutable."
        ),
        "http_method": "PATCH",
        "route_pattern": "/api/v1/catalogue/countries/<country_id>/",
        "view_import_path": "institutions.views.CountryDetailView",
        "risk_level": "high",
        "dependencies": [_dep("institutions.country.read", "The country must be readable before it can be edited.")],
        "change_summary": "Initial registration of the country update endpoint.",
        "change_reason": _PHASE,
    },
    # --- Institution ------------------------------------------------------
    {
        **_BASE,
        "model_key": "institution",
        "model_display_name": "Institution",
        "endpoint_key": "catalogue-institution-list",
        "permission_key": "institutions.institution.list",
        "operation_type": "list",
        "display_name": "List Institutions",
        "description": "List providers, filterable by country, type, availability, and name search.",
        "http_method": "GET",
        "route_pattern": "/api/v1/catalogue/institutions/",
        "view_import_path": "institutions.views.InstitutionListCreateView",
        "risk_level": "low",
        "dependencies": [_LOGIN],
        "change_summary": "Initial registration of the institution list endpoint.",
        "change_reason": _PHASE,
    },
    {
        **_BASE,
        "model_key": "institution",
        "model_display_name": "Institution",
        "endpoint_key": "catalogue-institution-create",
        "permission_key": "institutions.institution.create",
        "operation_type": "create",
        "display_name": "Create Institution",
        "description": "Add a provider under an existing country. Admin only.",
        "http_method": "POST",
        "route_pattern": "/api/v1/catalogue/institutions/",
        "view_import_path": "institutions.views.InstitutionListCreateView",
        "risk_level": "medium",
        "dependencies": [
            _dep("institutions.institution.list", "Creating institutions requires the ability to list them."),
            _dep("institutions.country.read", "An institution must be attached to an existing country."),
        ],
        "change_summary": "Initial registration of the institution create endpoint.",
        "change_reason": _PHASE,
    },
    {
        **_BASE,
        "model_key": "institution",
        "model_display_name": "Institution",
        "endpoint_key": "catalogue-institution-read",
        "permission_key": "institutions.institution.read",
        "operation_type": "read",
        "display_name": "View Institution",
        "description": "Retrieve one provider with its country and availability.",
        "http_method": "GET",
        "route_pattern": "/api/v1/catalogue/institutions/<institution_id>/",
        "view_import_path": "institutions.views.InstitutionDetailView",
        "risk_level": "low",
        "dependencies": [_dep("institutions.institution.list", "Reading an institution requires list access.")],
        "change_summary": "Initial registration of the institution read endpoint.",
        "change_reason": _PHASE,
    },
    {
        **_BASE,
        "model_key": "institution",
        "model_display_name": "Institution",
        "endpoint_key": "catalogue-institution-update",
        "permission_key": "institutions.institution.update",
        "operation_type": "update",
        "display_name": "Edit Institution",
        "description": (
            "Correct a provider's name, type, country, notes, or availability. "
            "Setting a non-active status requires a note."
        ),
        "http_method": "PATCH",
        "route_pattern": "/api/v1/catalogue/institutions/<institution_id>/",
        "view_import_path": "institutions.views.InstitutionDetailView",
        "risk_level": "high",
        "dependencies": [
            _dep("institutions.institution.read", "The institution must be readable before it can be edited.")
        ],
        "change_summary": "Initial registration of the institution update endpoint.",
        "change_reason": _PHASE,
    },
    # --- Campus -----------------------------------------------------------
    {
        **_BASE,
        "model_key": "campus",
        "model_display_name": "Campus",
        "endpoint_key": "catalogue-campus-list",
        "permission_key": "institutions.campus.list",
        "operation_type": "list",
        "display_name": "List Campuses",
        "description": "List one institution's sites. Nested under the institution that owns them.",
        "http_method": "GET",
        "route_pattern": "/api/v1/catalogue/institutions/<institution_id>/campuses/",
        "view_import_path": "institutions.views.CampusListCreateView",
        "risk_level": "low",
        "dependencies": [_dep("institutions.institution.read", "Campuses are listed within one institution.")],
        "change_summary": "Initial registration of the campus list endpoint.",
        "change_reason": _PHASE,
    },
    {
        **_BASE,
        "model_key": "campus",
        "model_display_name": "Campus",
        "endpoint_key": "catalogue-campus-create",
        "permission_key": "institutions.campus.create",
        "operation_type": "create",
        "display_name": "Create Campus",
        "description": "Add a site to a provider. The institution comes from the URL and never changes. Admin only.",
        "http_method": "POST",
        "route_pattern": "/api/v1/catalogue/institutions/<institution_id>/campuses/",
        "view_import_path": "institutions.views.CampusListCreateView",
        "risk_level": "medium",
        "dependencies": [
            _dep("institutions.campus.list", "Creating campuses requires the ability to list them."),
            _dep("institutions.institution.read", "A campus must be created under an existing institution."),
        ],
        "change_summary": "Initial registration of the campus create endpoint.",
        "change_reason": _PHASE,
    },
    {
        **_BASE,
        "model_key": "campus",
        "model_display_name": "Campus",
        "endpoint_key": "catalogue-campus-read",
        "permission_key": "institutions.campus.read",
        "operation_type": "read",
        "display_name": "View Campus",
        "description": "Retrieve one site with its institution and availability.",
        "http_method": "GET",
        "route_pattern": "/api/v1/catalogue/campuses/<campus_id>/",
        "view_import_path": "institutions.views.CampusDetailView",
        "risk_level": "low",
        "dependencies": [_dep("institutions.campus.list", "Reading a campus requires list access.")],
        "change_summary": "Initial registration of the campus read endpoint.",
        "change_reason": _PHASE,
    },
    {
        **_BASE,
        "model_key": "campus",
        "model_display_name": "Campus",
        "endpoint_key": "catalogue-campus-update",
        "permission_key": "institutions.campus.update",
        "operation_type": "update",
        "display_name": "Edit Campus",
        "description": (
            "Correct a site's name, city, notes, or availability. "
            "The owning institution is immutable; a non-active status requires a note."
        ),
        "http_method": "PATCH",
        "route_pattern": "/api/v1/catalogue/campuses/<campus_id>/",
        "view_import_path": "institutions.views.CampusDetailView",
        "risk_level": "medium",
        "dependencies": [_dep("institutions.campus.read", "The campus must be readable before it can be edited.")],
        "change_summary": "Initial registration of the campus update endpoint.",
        "change_reason": _PHASE,
    },
    # --- Program: the shortlisting search ---------------------------------
    {
        **_BASE,
        "model_key": "program",
        "model_display_name": "Program",
        "endpoint_key": "catalogue-program-list",
        "permission_key": "institutions.program.list",
        "operation_type": "list",
        "display_name": "Search Programs",
        "description": (
            "The shortlisting search. Filters by country, institution, campus, level, field, availability, "
            "scholarship, tuition ceiling, and free-text query. Returns only usable records unless asked otherwise."
        ),
        "http_method": "GET",
        "route_pattern": "/api/v1/catalogue/programs/",
        "view_import_path": "institutions.views.ProgramListCreateView",
        "risk_level": "low",
        "dependencies": [_LOGIN],
        "change_summary": "Initial registration of the program search endpoint.",
        "change_reason": _PHASE,
    },
    {
        **_BASE,
        "model_key": "program",
        "model_display_name": "Program",
        "endpoint_key": "catalogue-program-create",
        "permission_key": "institutions.program.create",
        "operation_type": "create",
        "display_name": "Create Program",
        "description": (
            "Add a study offering under an institution, with optional campus, tuition, entry expectations, "
            "and scholarship notes. Admin only."
        ),
        "http_method": "POST",
        "route_pattern": "/api/v1/catalogue/programs/",
        "view_import_path": "institutions.views.ProgramListCreateView",
        "risk_level": "medium",
        "dependencies": [
            _dep("institutions.program.list", "Creating programs requires the ability to list them."),
            _dep("institutions.institution.read", "A program must be attached to an existing institution."),
            _dep("institutions.field.read", "A program must be classified under an existing study field."),
        ],
        "change_summary": "Initial registration of the program create endpoint.",
        "change_reason": _PHASE,
    },
    {
        **_BASE,
        "model_key": "program",
        "model_display_name": "Program",
        "endpoint_key": "catalogue-program-read",
        "permission_key": "institutions.program.read",
        "operation_type": "read",
        "display_name": "View Program",
        "description": "Retrieve one program with its full entry expectations, tuition caveats, and notes.",
        "http_method": "GET",
        "route_pattern": "/api/v1/catalogue/programs/<program_id>/",
        "view_import_path": "institutions.views.ProgramDetailView",
        "risk_level": "low",
        "dependencies": [_dep("institutions.program.list", "Reading a program requires list access.")],
        "change_summary": "Initial registration of the program read endpoint.",
        "change_reason": _PHASE,
    },
    {
        **_BASE,
        "model_key": "program",
        "model_display_name": "Program",
        "endpoint_key": "catalogue-program-update",
        "permission_key": "institutions.program.update",
        "operation_type": "update",
        "display_name": "Edit Program",
        "description": (
            "Correct a program's classification, duration, intake, tuition, entry expectations, scholarship, "
            "or availability. The institution is immutable; a campus must belong to it; "
            "a tuition amount requires a currency and period."
        ),
        "http_method": "PATCH",
        "route_pattern": "/api/v1/catalogue/programs/<program_id>/",
        "view_import_path": "institutions.views.ProgramDetailView",
        "risk_level": "high",
        "dependencies": [_dep("institutions.program.read", "The program must be readable before it can be edited.")],
        "change_summary": "Initial registration of the program update endpoint.",
        "change_reason": _PHASE,
    },
]
