# Generated by Django 5.1.9 on 2026-07-23 21:02

import uuid

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("seasonal", "Seasonal"),
                            ("inactive", "Inactive"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "availability_note",
                    models.TextField(
                        blank=True,
                        help_text="Why this record is paused, seasonal, or inactive. Required whenever it is not active.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_code",
                                message="Code must be ASCII: lowercase letters, digits, and _ - only, starting and ending with a letter or digit.",
                                regex="^[a-z0-9](?:[a-z0-9_-]{0,48}[a-z0-9])?$",
                            )
                        ],
                    ),
                ),
                ("name_en", models.CharField(max_length=150)),
                (
                    "name_np",
                    models.CharField(
                        blank=True,
                        help_text="Optional. Destinations are one of the few catalogue names staff do write in Nepali.",
                        max_length=150,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "db_table": "institutions_country",
                "ordering": ["display_order", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_code",
                                message="Code must be ASCII: lowercase letters, digits, and _ - only, starting and ending with a letter or digit.",
                                regex="^[a-z0-9](?:[a-z0-9_-]{0,48}[a-z0-9])?$",
                            )
                        ],
                    ),
                ),
                ("name_en", models.CharField(max_length=150)),
                ("name_np", models.CharField(blank=True, max_length=150)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Study Field",
                "verbose_name_plural": "Study Fields",
                "db_table": "institutions_field",
                "ordering": ["display_order", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("seasonal", "Seasonal"),
                            ("inactive", "Inactive"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "availability_note",
                    models.TextField(
                        blank=True,
                        help_text="Why this record is paused, seasonal, or inactive. Required whenever it is not active.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("name_en", models.CharField(max_length=255)),
                ("name_np", models.CharField(blank=True, max_length=255)),
                (
                    "common_name",
                    models.CharField(
                        blank=True, help_text='What staff actually call it, e.g. "Unimelb".', max_length=150
                    ),
                ),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("university", "University"),
                            ("college", "College"),
                            ("polytechnic", "Polytechnic"),
                            ("language_school", "Language School"),
                            ("other", "Other"),
                        ],
                        default="university",
                        max_length=20,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="institutions",
                        to="institutions.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Institution",
                "verbose_name_plural": "Institutions",
                "db_table": "institutions_institution",
                "ordering": ["name_en"],
            },
        ),
        migrations.CreateModel(
            name="Campus",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("seasonal", "Seasonal"),
                            ("inactive", "Inactive"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "availability_note",
                    models.TextField(
                        blank=True,
                        help_text="Why this record is paused, seasonal, or inactive. Required whenever it is not active.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("name_en", models.CharField(max_length=255)),
                ("city", models.CharField(blank=True, max_length=150)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campuses",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campus",
                "verbose_name_plural": "Campuses",
                "db_table": "institutions_campus",
                "ordering": ["name_en"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("seasonal", "Seasonal"),
                            ("inactive", "Inactive"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "availability_note",
                    models.TextField(
                        blank=True,
                        help_text="Why this record is paused, seasonal, or inactive. Required whenever it is not active.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "qualification_level",
                    models.CharField(
                        choices=[
                            ("school", "School"),
                            ("certificate", "Certificate"),
                            ("diploma", "Diploma"),
                            ("bachelors", "Bachelor's"),
                            ("postgraduate_diploma", "Postgraduate Diploma"),
                            ("masters", "Master's"),
                            ("phd", "PhD"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        help_text="Same vocabulary as ApplicantJourney.study_level, so the two can be matched directly.",
                        max_length=30,
                    ),
                ),
                (
                    "duration_months",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "intake_pattern",
                    models.CharField(
                        blank=True,
                        help_text='Free text until intakes are catalogued, e.g. "Feb / Jul".',
                        max_length=100,
                    ),
                ),
                ("tuition_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                (
                    "tuition_currency",
                    models.CharField(
                        blank=True,
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_currency",
                                message="Currency must be a three-letter ISO 4217 code, e.g. AUD.",
                                regex="^[A-Z]{3}$",
                            )
                        ],
                    ),
                ),
                (
                    "tuition_fee_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("per_year", "Per Year"),
                            ("per_semester", "Per Semester"),
                            ("total_program", "Total Program"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tuition_is_indicative",
                    models.BooleanField(
                        default=False, help_text="True when the figure is an estimate rather than a quoted fee."
                    ),
                ),
                (
                    "tuition_notes",
                    models.TextField(
                        blank=True,
                        help_text="Caveats. The concept asks that both the value and its context be preserved.",
                    ),
                ),
                ("academic_requirement", models.TextField(blank=True)),
                ("english_requirement", models.TextField(blank=True)),
                ("backlog_tolerance", models.TextField(blank=True)),
                ("document_expectation", models.TextField(blank=True)),
                ("selection_notes", models.TextField(blank=True)),
                ("scholarship_available", models.BooleanField(default=False)),
                ("scholarship_notes", models.TextField(blank=True)),
                (
                    "campus",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional. Set only when the institution splits programs by campus.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programs",
                        to="institutions.campus",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="programs", to="institutions.field"
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programs",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program",
                "verbose_name_plural": "Programs",
                "db_table": "institutions_program",
                "ordering": ["title"],
            },
        ),
        migrations.AddIndex(
            model_name="institution",
            index=models.Index(fields=["country", "availability_status"], name="institution_country_status_idx"),
        ),
        migrations.AddIndex(
            model_name="institution",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name_en"], name="institution_name_en_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="institution",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name_np"], name="institution_name_np_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="campus",
            index=models.Index(fields=["institution", "availability_status"], name="campus_institution_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="campus",
            constraint=models.UniqueConstraint(fields=("institution", "name_en"), name="campus_institution_name_uniq"),
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(fields=["institution", "availability_status"], name="program_institution_status_idx"),
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(fields=["qualification_level", "availability_status"], name="program_level_status_idx"),
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(fields=["field", "availability_status"], name="program_field_status_idx"),
        ),
        migrations.AddIndex(
            model_name="program",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="program_title_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
