# Generated by Django 5.1.9 on 2026-07-24 16:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("checklist_item_due", "Checklist Item Due"),
                            ("checklist_item_overdue", "Checklist Item Overdue"),
                            ("missing_documents", "Missing Documents"),
                            ("offer_response_due", "Offer Response Due"),
                            ("offer_expired", "Offer Response Overdue"),
                            ("passport_expiring", "Passport Expiring"),
                            ("assignment_received", "Assignment Received"),
                            ("file_rejected", "File Rejected"),
                            ("journey_stage_changed", "Journey Stage Changed"),
                            ("journey_closed", "Journey Closed"),
                            ("offer_decided", "Offer Decided"),
                            ("missing_information", "Missing Information"),
                            ("appointment_reminder", "Appointment Reminder"),
                            ("test_score_expiring", "Test Score Expiring"),
                        ],
                        db_index=True,
                        help_text="Drives priority, grouping, and iconography — never business logic.",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Low"), ("normal", "Normal"), ("high", "High"), ("urgent", "Urgent")],
                        db_index=True,
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(help_text="What happened, in one line.", max_length=200)),
                ("body", models.TextField(blank=True, help_text="Why it needs attention and what to do next.")),
                (
                    "source_app",
                    models.CharField(help_text="The app that owns the record, e.g. 'checklists'.", max_length=50),
                ),
                (
                    "source_entity_type",
                    models.CharField(
                        help_text="The record kind, e.g. 'checklist_item'. Shares audit.AuditEvent's vocabulary by convention.",
                        max_length=50,
                    ),
                ),
                ("source_entity_id", models.UUIDField(blank=True, null=True)),
                (
                    "source_api_path",
                    models.CharField(
                        blank=True,
                        help_text="Canonical API path of the source, so a client is not guessing routes.",
                        max_length=255,
                    ),
                ),
                (
                    "due_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When this becomes urgent, copied from the source deadline. Null for a lifecycle alert.",
                        null=True,
                    ),
                ),
                ("read_at", models.DateTimeField(blank=True, help_text="Null means unread.", null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("dismissed", "Dismissed"), ("resolved", "Resolved")],
                        db_index=True,
                        default="active",
                        max_length=15,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("source_cleared", "Source condition cleared"),
                            ("dismissed_by_user", "Dismissed by user"),
                        ],
                        help_text="Why it stopped being active. Blank while active.",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery_channel",
                    models.CharField(choices=[("in_app", "In-App")], default="in_app", max_length=15),
                ),
                (
                    "delivery_state",
                    models.CharField(
                        choices=[("pending", "Pending"), ("delivered", "Delivered"), ("failed", "Failed")],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dedupe_key",
                    models.CharField(
                        help_text="'<type>:<entity_type>:<entity_id>[:<discriminator>]'. Unique per recipient.",
                        max_length=255,
                    ),
                ),
                (
                    "generated_by",
                    models.CharField(
                        choices=[("sweep", "Deadline sweep"), ("signal", "Source event")],
                        db_index=True,
                        help_text="The sweep's resolve pass only ever touches 'sweep' rows.",
                        max_length=10,
                    ),
                ),
                (
                    "dismissed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set only on a manual dismiss. Always equals recipient today.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications_dismissed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="Who must act. Users are deactivated, never deleted, so PROTECT never fires in practice.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications_notification",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["recipient", "status", "-created_at"], name="notif_feed_idx"),
                    models.Index(fields=["recipient", "read_at"], name="notif_unread_idx"),
                    models.Index(fields=["status", "due_at"], name="notif_status_due_idx"),
                    models.Index(fields=["source_entity_type", "source_entity_id"], name="notif_source_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recipient", "dedupe_key"), name="notification_one_per_recipient_key"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("resolution", ""), ("resolved_at__isnull", True), ("status", "active")),
                            models.Q(
                                ("resolved_at__isnull", False),
                                ("status__in", ("dismissed", "resolved")),
                                models.Q(("resolution", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="notification_resolution_matches_status",
                    ),
                ],
            },
        ),
    ]
