# Generated by Django 5.2.17 on 2026-08-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("checklist_item_due", "Checklist Item Due"),
                    ("checklist_item_overdue", "Checklist Item Overdue"),
                    ("missing_documents", "Missing Documents"),
                    ("offer_response_due", "Offer Response Due"),
                    ("offer_expired", "Offer Response Overdue"),
                    ("passport_expiring", "Passport Expiring"),
                    ("custom_reminder", "Custom Reminder"),
                    ("assignment_received", "Assignment Received"),
                    ("file_rejected", "File Rejected"),
                    ("journey_stage_changed", "Journey Stage Changed"),
                    ("journey_closed", "Journey Closed"),
                    ("offer_decided", "Offer Decided"),
                    ("missing_information", "Missing Information"),
                    ("appointment_reminder", "Appointment Reminder"),
                    ("test_score_expiring", "Test Score Expiring"),
                ],
                db_index=True,
                help_text="Drives priority, grouping, and iconography — never business logic.",
                max_length=30,
            ),
        ),
    ]
