# Generated by Django 5.1.9 on 2026-07-24 13:59

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("applicant_journeys", "0002_target_country_ref"),
        ("institutions", "0001_initial"),
        ("uploaded_files", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        help_text="Stable ASCII identifier, e.g. 'australia-student-visa'.",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_template_key",
                                message="Key must be ASCII: lowercase letters, digits, and _ - only, starting and ending with a letter or digit.",
                                regex="^[a-z0-9](?:[a-z0-9_-]{0,48}[a-z0-9])?$",
                            )
                        ],
                    ),
                ),
                (
                    "label",
                    models.CharField(help_text="What staff see, e.g. 'Australia — Student Visa'.", max_length=200),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="The list this country's applicants inherit automatically. At most one active default per country.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "status_note",
                    models.TextField(
                        blank=True,
                        help_text="Why this template is in its current state. Optional — no transition here requires one.",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="The destination this list is for. Null means a general list, applied only by hand.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklist_templates",
                        to="institutions.country",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklist_templates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklist Template",
                "verbose_name_plural": "Checklist Templates",
                "db_table": "checklists_checklisttemplate",
                "ordering": ["display_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="Checklist",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "origin",
                    models.CharField(
                        choices=[("auto", "Inherited automatically"), ("manual", "Created by staff")],
                        db_index=True,
                        default="manual",
                        help_text="Whether this was inherited automatically or created by staff.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("archive_reason", models.TextField(blank=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status_before_archive",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklists_archived",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklists_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklists_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="Copied from the template at instantiation. Not re-read later.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklists",
                        to="institutions.country",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklists_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklists",
                        to="applicant_journeys.applicantjourney",
                    ),
                ),
                (
                    "source_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="The template this was inherited from. Null for a checklist staff built by hand.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklists",
                        to="checklists.checklisttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklist",
                "verbose_name_plural": "Checklists",
                "db_table": "checklists_checklist",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistTemplateItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(help_text="The requirement, e.g. 'Passport bio page scan'.", max_length=255),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("document", "Document"), ("stage", "Stage"), ("task", "Task")],
                        default="document",
                        max_length=20,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="Required items must be resolved before the checklist can be completed.",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "default_due_offset_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Days after instantiation this item is due. Turned into a real date on each applicant's copy.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="checklists.checklisttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklist Template Item",
                "verbose_name_plural": "Checklist Template Items",
                "db_table": "checklists_checklisttemplateitem",
                "ordering": ["display_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("document", "Document"), ("stage", "Stage"), ("task", "Task")],
                        default="document",
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("waived", "Waived"),
                            ("blocked", "Blocked"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "status_note",
                    models.TextField(
                        blank=True, help_text="Why this item was waived or declared blocked. Required for both."
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("evidence_note", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklist_items_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="checklists.checklist"
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklist_items_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evidence_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklist_items",
                        to="uploaded_files.uploadedfile",
                    ),
                ),
                (
                    "source_template_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which definition this was copied from. Null for an item staff added by hand.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="checklists.checklisttemplateitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklist Item",
                "verbose_name_plural": "Checklist Items",
                "db_table": "checklists_checklistitem",
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="checklisttemplate",
            index=models.Index(fields=["country", "status"], name="cl_template_country_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="checklisttemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True), ("status", "active")),
                fields=("country",),
                name="checklist_one_active_default_per_country",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklisttemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_default", False), ("country__isnull", False), _connector="OR"),
                name="checklist_default_requires_country",
            ),
        ),
        migrations.AddIndex(
            model_name="checklist",
            index=models.Index(fields=["journey", "-created_at"], name="cl_journey_recent_idx"),
        ),
        migrations.AddIndex(
            model_name="checklist",
            index=models.Index(fields=["status", "-created_at"], name="cl_status_recent_idx"),
        ),
        migrations.AddIndex(
            model_name="checklist",
            index=models.Index(fields=["assigned_to", "status"], name="cl_assignee_status_idx"),
        ),
        migrations.AddIndex(
            model_name="checklist",
            index=models.Index(fields=["country", "status"], name="cl_country_status_idx"),
        ),
        migrations.AddIndex(
            model_name="checklist",
            index=models.Index(fields=["due_at"], name="cl_due_idx"),
        ),
        migrations.AddIndex(
            model_name="checklisttemplateitem",
            index=models.Index(fields=["template", "display_order"], name="cl_tmpl_item_order_idx"),
        ),
        migrations.AddIndex(
            model_name="checklistitem",
            index=models.Index(fields=["checklist", "display_order"], name="cl_item_order_idx"),
        ),
        migrations.AddIndex(
            model_name="checklistitem",
            index=models.Index(fields=["status", "due_at"], name="cl_item_status_due_idx"),
        ),
        migrations.AddIndex(
            model_name="checklistitem",
            index=models.Index(fields=["assigned_to", "status"], name="cl_item_assignee_idx"),
        ),
    ]
