# Generated by Django 5.1.9 on 2026-06-19 11:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PolicyApplication",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("current_version", models.CharField(default="1.0.0", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deprecated", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Policy Application",
                "verbose_name_plural": "Policy Applications",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="PolicyModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=100)),
                ("import_path", models.CharField(blank=True, max_length=500)),
                ("display_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("current_version", models.CharField(default="1.0.0", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deprecated", models.BooleanField(default=False)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_models",
                        to="policy_engine.policyapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Model",
                "verbose_name_plural": "Policy Models",
                "ordering": ["application__key", "key"],
                "unique_together": {("application", "key")},
            },
        ),
        migrations.CreateModel(
            name="PolicyEndpoint",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=100)),
                ("permission_key", models.CharField(db_index=True, max_length=255, unique=True)),
                ("http_method", models.CharField(blank=True, max_length=20)),
                ("route_pattern", models.CharField(blank=True, max_length=500)),
                ("view_import_path", models.CharField(blank=True, max_length=500)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("read", "Read"),
                            ("list", "List"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("custom", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("current_version", models.CharField(default="1.0.0", max_length=50)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                        default="low",
                        max_length=50,
                    ),
                ),
                ("is_internal", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deprecated", models.BooleanField(default=False)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoints",
                        to="policy_engine.policyapplication",
                    ),
                ),
                (
                    "policy_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="endpoints",
                        to="policy_engine.policymodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Endpoint",
                "verbose_name_plural": "Policy Endpoints",
                "ordering": ["application__key", "key"],
                "unique_together": {("application", "key")},
            },
        ),
        migrations.CreateModel(
            name="PolicyChangeLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("application", "Application"),
                            ("model", "Model"),
                            ("endpoint", "Endpoint"),
                            ("category", "Category"),
                            ("dependency", "Dependency"),
                        ],
                        max_length=50,
                    ),
                ),
                ("object_key", models.CharField(blank=True, max_length=255)),
                ("previous_version", models.CharField(blank=True, max_length=50)),
                ("new_version", models.CharField(blank=True, max_length=50)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("bug_fix", "Bug Fix"),
                            ("security_fix", "Security Fix"),
                            ("route_changed", "Route Changed"),
                            ("method_changed", "Method Changed"),
                            ("dependency_added", "Dependency Added"),
                            ("dependency_removed", "Dependency Removed"),
                            ("category_changed", "Category Changed"),
                            ("deprecated", "Deprecated"),
                            ("removed", "Removed"),
                            ("restored", "Restored"),
                            ("breaking_change", "Breaking Change"),
                            ("metadata_update", "Metadata Update"),
                        ],
                        max_length=100,
                    ),
                ),
                ("summary", models.CharField(max_length=500)),
                ("detail", models.TextField(blank=True)),
                ("reason", models.TextField(blank=True)),
                ("issue_reference", models.CharField(blank=True, max_length=255)),
                ("migration_reference", models.CharField(blank=True, max_length=255)),
                ("affected_dependencies", models.JSONField(blank=True, default=list)),
                ("affected_categories", models.JSONField(blank=True, default=list)),
                ("backward_compatibility_notes", models.TextField(blank=True)),
                ("forward_compatibility_notes", models.TextField(blank=True)),
                (
                    "created_by_type",
                    models.CharField(
                        choices=[("human", "Human"), ("ai", "AI"), ("system", "System")],
                        default="system",
                        max_length=50,
                    ),
                ),
                ("created_by_identifier", models.CharField(blank=True, max_length=255)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="changelogs",
                        to="policy_engine.policyapplication",
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="changelogs",
                        to="policy_engine.policyendpoint",
                    ),
                ),
                (
                    "policy_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="changelogs",
                        to="policy_engine.policymodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Change Log",
                "verbose_name_plural": "Policy Change Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PermissionCategory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("icon_key", models.CharField(blank=True, max_length=100)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deprecated", models.BooleanField(default=False)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="policy_engine.permissioncategory",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="policy_engine.policyapplication",
                    ),
                ),
                (
                    "policy_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="categories",
                        to="policy_engine.policymodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Category",
                "verbose_name_plural": "Permission Categories",
                "ordering": ["sort_order", "key"],
            },
        ),
        migrations.CreateModel(
            name="PolicyDependency",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("forward", "Forward"), ("backward", "Backward"), ("bidirectional", "Bidirectional")],
                        max_length=50,
                    ),
                ),
                (
                    "dependency_type",
                    models.CharField(
                        choices=[
                            ("requires", "Requires"),
                            ("implies", "Implies"),
                            ("conflicts_with", "Conflicts With"),
                            ("revokes_with", "Revokes With"),
                            ("suggests", "Suggests"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "enforcement_mode",
                    models.CharField(
                        choices=[
                            ("strict", "Strict"),
                            ("warning", "Warning"),
                            ("manual_review", "Manual Review"),
                            ("metadata_only", "Metadata Only"),
                        ],
                        default="strict",
                        max_length=50,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deprecated", models.BooleanField(default=False)),
                (
                    "source_endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_dependencies",
                        to="policy_engine.policyendpoint",
                    ),
                ),
                (
                    "target_endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_dependencies",
                        to="policy_engine.policyendpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Dependency",
                "verbose_name_plural": "Policy Dependencies",
                "ordering": ["source_endpoint__permission_key", "target_endpoint__permission_key"],
                "unique_together": {("source_endpoint", "target_endpoint", "direction", "dependency_type")},
            },
        ),
        migrations.CreateModel(
            name="EndpointCategoryMap",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_label", models.CharField(max_length=255)),
                ("help_text", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_visible_in_ui", models.BooleanField(default=True)),
                ("is_sensitive", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoint_maps",
                        to="policy_engine.permissioncategory",
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_maps",
                        to="policy_engine.policyendpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Endpoint Category Map",
                "verbose_name_plural": "Endpoint Category Maps",
                "ordering": ["sort_order"],
                "unique_together": {("endpoint", "category")},
            },
        ),
        migrations.CreateModel(
            name="PolicyEndpointVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(max_length=50)),
                ("route_pattern", models.CharField(blank=True, max_length=500)),
                ("http_method", models.CharField(blank=True, max_length=20)),
                ("view_import_path", models.CharField(blank=True, max_length=500)),
                ("operation_type", models.CharField(max_length=50)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("is_current", models.BooleanField(default=False)),
                ("is_deprecated", models.BooleanField(default=False)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="policy_engine.policyendpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Endpoint Version",
                "verbose_name_plural": "Policy Endpoint Versions",
                "ordering": ["-created_at"],
                "unique_together": {("endpoint", "version")},
            },
        ),
    ]
