# Generated by Django 5.1.9 on 2026-06-19 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policy_engine", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policychangelog",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="changelogs",
                to="policy_engine.policyapplication",
            ),
        ),
        migrations.AlterField(
            model_name="policychangelog",
            name="endpoint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="changelogs",
                to="policy_engine.policyendpoint",
            ),
        ),
        migrations.AlterField(
            model_name="policychangelog",
            name="policy_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="changelogs",
                to="policy_engine.policymodel",
            ),
        ),
        migrations.AlterField(
            model_name="policyendpointversion",
            name="endpoint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="versions", to="policy_engine.policyendpoint"
            ),
        ),
    ]
