# Generated by Django 5.1.9 on 2026-06-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policy_engine", "0002_protect_append_only_fks"),
    ]

    operations = [
        migrations.AddField(
            model_name="policyendpoint",
            name="is_dependency_root",
            field=models.BooleanField(
                default=False,
                help_text="True for endpoints that legitimately have no prerequisite permission (e.g. login) — exempts a high/critical-risk endpoint from the 'must declare a dependency' validation rule.",
            ),
        ),
    ]
