# Generated by Django 5.1.9 on 2026-07-13 12:00
#
# Destructive: drops PolicyEndpointVersion.is_current (approved 2026-07-13).
# The column was unusable — the model's append-only guards rejected every write
# path that tried to flip it. Currency is now derived: a version record is
# "current" iff its version equals endpoint.current_version.
# Rollback: re-add the BooleanField(default=False), then backfill True on each
# record whose version matches its endpoint's current_version.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("policy_engine", "0003_policyendpoint_is_dependency_root"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="policyendpointversion",
            name="is_current",
        ),
    ]
