# Generated by Django 5.1.9 on 2026-07-13 18:07
#
# Additive, non-destructive: both fields blank-default. branch_name and
# based_on_commit_sha are auto-captured by log_change() via a best-effort git
# subprocess call — see core/policy_engine/docs/DATA_CONTRACT.md §8
# "Provenance rule". Rollback: RemoveField both columns, no data migration
# needed (existing rows simply have no provenance captured).

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policy_engine", "0004_remove_endpointversion_is_current"),
    ]

    operations = [
        migrations.AddField(
            model_name="policychangelog",
            name="based_on_commit_sha",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="policychangelog",
            name="branch_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
