# Generated by Django 5.1.9 on 2026-07-23 10:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("applicants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicantJourney",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target_country", models.CharField(blank=True, max_length=100)),
                ("target_institution_name", models.CharField(blank=True, max_length=255)),
                ("target_program_name", models.CharField(blank=True, max_length=255)),
                (
                    "study_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("school", "School"),
                            ("certificate", "Certificate"),
                            ("diploma", "Diploma"),
                            ("bachelors", "Bachelor's"),
                            ("postgraduate_diploma", "Postgraduate Diploma"),
                            ("masters", "Master's"),
                            ("phd", "PhD"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("field_of_study", models.CharField(blank=True, max_length=150)),
                (
                    "preferred_intake",
                    models.CharField(
                        blank=True,
                        help_text='Free text until intakes are catalogued, e.g. "Fall 2026".',
                        max_length=50,
                    ),
                ),
                ("budget_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("budget_currency", models.CharField(blank=True, help_text="ISO 4217 code, e.g. NPR.", max_length=3)),
                ("scholarship_interest", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("profile_building", "Profile Building"),
                            ("shortlisting", "Shortlisting"),
                            ("applying", "Applying"),
                            ("offer_stage", "Offer Stage"),
                            ("visa_stage", "Visa Stage"),
                            ("completed", "Completed"),
                            ("closed", "Closed"),
                            ("deferred", "Deferred"),
                        ],
                        db_index=True,
                        default="planning",
                        max_length=30,
                    ),
                ),
                (
                    "creation_source",
                    models.CharField(
                        choices=[("lead_conversion", "Lead Conversion"), ("manual", "Manual")], max_length=20
                    ),
                ),
                ("deferred_at", models.DateTimeField(blank=True, null=True)),
                ("deferred_to_intake", models.CharField(blank=True, max_length=50)),
                ("deferment_reason", models.TextField(blank=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("successful", "Successful"),
                            ("withdrawn", "Withdrawn"),
                            ("rejected", "Rejected"),
                            ("not_qualified", "Not Qualified"),
                            ("cancelled", "Cancelled"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("closure_reason", models.TextField(blank=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stage_before_terminal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("planning", "Planning"),
                            ("profile_building", "Profile Building"),
                            ("shortlisting", "Shortlisting"),
                            ("applying", "Applying"),
                            ("offer_stage", "Offer Stage"),
                            ("visa_stage", "Visa Stage"),
                            ("completed", "Completed"),
                            ("closed", "Closed"),
                            ("deferred", "Deferred"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="journeys", to="applicants.applicant"
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journeys_closed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journeys_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deferred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journeys_deferred",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Applicant Journey",
                "verbose_name_plural": "Applicant Journeys",
                "db_table": "applicant_journeys_applicantjourney",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["applicant", "-created_at"], name="journey_applicant_recent_idx"),
                    models.Index(fields=["stage", "-created_at"], name="journey_stage_recent_idx"),
                ],
            },
        ),
    ]
