# Generated by Django 5.1.9 on 2026-07-22 13:11

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import authenticate.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_username",
                                message="Username must be ASCII: lowercase letters, digits, and . _ - only, starting and ending with a letter or digit.",
                                regex="^[a-z0-9](?:[a-z0-9._-]{1,148}[a-z0-9])?$",
                            )
                        ],
                    ),
                ),
                (
                    "authority_type",
                    models.CharField(
                        choices=[("superadmin", "Superadmin"), ("admin", "Admin"), ("lead_manager", "Lead Manager")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("full_name_np", models.CharField(blank=True, max_length=255)),
                ("full_name_en", models.CharField(blank=True, max_length=255)),
                ("full_name_romanized", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "authenticate_user",
            },
            managers=[
                ("objects", authenticate.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AuthEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("superadmin_bootstrap", "Superadmin Bootstrap"),
                            ("login_success", "Login Success"),
                            ("login_failure", "Login Failure"),
                            ("forced_password_change", "Forced Password Change"),
                            ("password_change", "Password Change"),
                            ("logout", "Logout"),
                            ("session_refreshed", "Session Refreshed"),
                            ("session_revoked", "Session Revoked"),
                            ("account_blocked", "Account Blocked"),
                            ("account_restored", "Account Restored"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("subject_username", models.CharField(blank=True, db_index=True, max_length=150)),
                ("success", models.BooleanField(default=True)),
                ("reason", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_id", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auth_events_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auth_events_about",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auth Event",
                "verbose_name_plural": "Auth Events",
                "db_table": "authenticate_authevent",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSecurityState",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("must_change_password", models.BooleanField(default=True)),
                ("password_changed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provisioned_via",
                    models.CharField(
                        choices=[
                            ("bootstrap_command", "Bootstrap Command"),
                            ("superadmin_created", "Created by Superadmin"),
                            ("admin_created", "Created by Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                ("blocked_at", models.DateTimeField(blank=True, null=True)),
                ("blocked_reason", models.TextField(blank=True)),
                (
                    "blocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocks_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_state",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Security State",
                "verbose_name_plural": "User Security States",
                "db_table": "authenticate_usersecuritystate",
            },
        ),
        migrations.CreateModel(
            name="AuthSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("device_id", models.CharField(db_index=True, max_length=255)),
                ("device_name", models.CharField(blank=True, max_length=255)),
                ("refresh_token_hash", models.CharField(max_length=64, unique=True)),
                ("family_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revoked_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("logout", "Logout"),
                            ("password_change", "Password Change"),
                            ("replaced_same_device", "Replaced (same device re-login)"),
                            ("rotated", "Rotated (normal refresh rotation)"),
                            ("rotated_reuse", "Rotated token reuse detected"),
                            ("device_limit", "Device limit enforcement"),
                            ("blocked", "Account blocked"),
                            ("admin_revoked", "Revoked by administrator"),
                        ],
                        max_length=30,
                    ),
                ),
                ("last_used_at", models.DateTimeField(auto_now_add=True)),
                ("idle_expires_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                (
                    "previous_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="authenticate.authsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auth Session",
                "verbose_name_plural": "Auth Sessions",
                "db_table": "authenticate_authsession",
                "indexes": [models.Index(fields=["user", "is_active"], name="authenticat_user_id_692985_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("user", "device_id"),
                        name="uniq_active_session_per_device",
                    )
                ],
            },
        ),
    ]
