# Generated by Django 5.1.9 on 2026-07-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("superadmin_bootstrap", "Superadmin Bootstrap"),
                    ("login_success", "Login Success"),
                    ("login_failure", "Login Failure"),
                    ("forced_password_change", "Forced Password Change"),
                    ("password_change", "Password Change"),
                    ("logout", "Logout"),
                    ("session_refreshed", "Session Refreshed"),
                    ("session_revoked", "Session Revoked"),
                    ("account_blocked", "Account Blocked"),
                    ("account_restored", "Account Restored"),
                    ("mfa_enabled", "MFA Enabled"),
                    ("mfa_disabled", "MFA Disabled"),
                    ("mfa_verification_failure", "MFA Verification Failure"),
                    ("mfa_reset", "MFA Reset (recovery)"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="authsession",
            name="revoked_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("logout", "Logout"),
                    ("password_change", "Password Change"),
                    ("replaced_same_device", "Replaced (same device re-login)"),
                    ("rotated", "Rotated (normal refresh rotation)"),
                    ("rotated_reuse", "Rotated token reuse detected"),
                    ("device_limit", "Device limit enforcement"),
                    ("blocked", "Account blocked"),
                    ("admin_revoked", "Revoked by administrator"),
                    ("mfa_change", "MFA changed (enabled/disabled/reset)"),
                ],
                max_length=30,
            ),
        ),
    ]
