# Generated by Django 5.1.9 on 2026-07-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0002_alter_authevent_event_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("superadmin_bootstrap", "Superadmin Bootstrap"),
                    ("login_success", "Login Success"),
                    ("login_failure", "Login Failure"),
                    ("forced_password_change", "Forced Password Change"),
                    ("password_change", "Password Change"),
                    ("logout", "Logout"),
                    ("session_refreshed", "Session Refreshed"),
                    ("session_revoked", "Session Revoked"),
                    ("account_created", "Account Created"),
                    ("account_updated", "Account Updated"),
                    ("account_blocked", "Account Blocked"),
                    ("account_restored", "Account Restored"),
                    ("admin_password_reset", "Administrative Password Reset"),
                    ("mfa_enabled", "MFA Enabled"),
                    ("mfa_disabled", "MFA Disabled"),
                    ("mfa_verification_failure", "MFA Verification Failure"),
                    ("mfa_reset", "MFA Reset (recovery)"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
