# Generated by Django 5.1.9 on 2026-07-22 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0003_alter_authevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="Username must be ASCII: lowercase letters, digits, and . _ - only, starting and ending with a letter or digit.",
                        regex="^[a-z0-9](?:[a-z0-9._-]{0,148}[a-z0-9])?$",
                    )
                ],
            ),
        ),
    ]
