# Generated by Django 5.1.9 on 2026-07-24 09:09

import uuid

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # Not a data relation — applicants.0001 is the earliest migration that creates the
        # pg_trgm extension the gin_trgm_ops indexes below are built on. Without it a fresh
        # database (CI, a new host) can run this migration first and fail with
        # 'operator class "gin_trgm_ops" does not exist'. Same precedent as uploaded_files.0001.
        ("applicants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name_np", models.CharField(max_length=255)),
                ("name_en", models.CharField(blank=True, max_length=255)),
                (
                    "name_romanized",
                    models.CharField(
                        blank=True,
                        help_text="Auto-populated from name_np by the service layer. A search aid, not a display field.",
                        max_length=255,
                    ),
                ),
                ("spokesperson_name_np", models.CharField(blank=True, max_length=255)),
                ("spokesperson_name_en", models.CharField(blank=True, max_length=255)),
                ("spokesperson_name_romanized", models.CharField(blank=True, max_length=255)),
                (
                    "spokesperson_designation",
                    models.CharField(
                        blank=True,
                        help_text='Their role at the client organization, e.g. "Managing Director".',
                        max_length=150,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True, max_length=500)),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        help_text="A link to a logo hosted elsewhere. Not an upload — see docs/DATA_CONTRACT.md.",
                        max_length=500,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="One free-text field, not the structured shape applicants uses. The concept asks for small.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "status_note",
                    models.TextField(
                        blank=True,
                        help_text="Why the relationship ended or paused. Required when retiring; cleared on restore.",
                    ),
                ),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clients_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients_retired",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "db_table": "clients_client",
                "ordering": ["name_np"],
            },
        ),
        migrations.CreateModel(
            name="ClientContactNumber",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_contact_number",
                                message="Contact number may contain digits, spaces, and + - ( ) only.",
                                regex="^\\+?[0-9][0-9 ()\\-]{4,31}$",
                            )
                        ],
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("home", "Home"),
                            ("work", "Work"),
                            ("whatsapp", "WhatsApp"),
                            ("viber", "Viber"),
                            ("other", "Other"),
                        ],
                        default="mobile",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_numbers",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Contact Number",
                "verbose_name_plural": "Client Contact Numbers",
                "db_table": "clients_clientcontactnumber",
                "ordering": ["-is_primary", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["status", "name_np"], name="client_status_name_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name_np"], name="client_name_np_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name_en"], name="client_name_en_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name_romanized"], name="client_name_rom_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddConstraint(
            model_name="clientcontactnumber",
            constraint=models.UniqueConstraint(fields=("client", "number"), name="uniq_client_contact_number"),
        ),
    ]
