# Generated by Django 5.1.9 on 2026-07-24 08:26

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("applicant_journeys", "0001_initial"),
        ("institutions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference_source",
                    models.CharField(
                        choices=[("catalogue", "From Catalogue"), ("manual", "Manual Entry")],
                        help_text="Whether this offer was built from the catalogue or typed in as a historical record.",
                        max_length=20,
                    ),
                ),
                ("institution_name_en", models.CharField(max_length=255)),
                ("institution_name_np", models.CharField(blank=True, max_length=255)),
                ("campus_name", models.CharField(blank=True, max_length=255)),
                ("program_title", models.CharField(max_length=255)),
                ("country_name", models.CharField(blank=True, max_length=150)),
                (
                    "qualification_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("school", "School"),
                            ("certificate", "Certificate"),
                            ("diploma", "Diploma"),
                            ("bachelors", "Bachelor's"),
                            ("postgraduate_diploma", "Postgraduate Diploma"),
                            ("masters", "Master's"),
                            ("phd", "PhD"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "intake_label",
                    models.CharField(
                        blank=True,
                        help_text='The intake this offer applies to, free text until intakes are catalogued, e.g. "Feb 2027".',
                        max_length=100,
                    ),
                ),
                (
                    "offer_type",
                    models.CharField(
                        choices=[("conditional", "Conditional"), ("unconditional", "Unconditional")],
                        default="conditional",
                        max_length=20,
                    ),
                ),
                (
                    "offer_reference",
                    models.CharField(
                        blank=True,
                        help_text="The institution's own offer or letter number, as printed on the document.",
                        max_length=100,
                    ),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                (
                    "response_deadline",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="The date by which the applicant must respond. Drives the overdue flag and deadline reporting.",
                        null=True,
                    ),
                ),
                ("tuition_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                (
                    "tuition_currency",
                    models.CharField(
                        blank=True,
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_currency",
                                message="Currency must be a three-letter ISO 4217 code, e.g. AUD.",
                                regex="^[A-Z]{3}$",
                            )
                        ],
                    ),
                ),
                (
                    "tuition_fee_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("per_year", "Per Year"),
                            ("per_semester", "Per Semester"),
                            ("total_program", "Total Program"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scholarship_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                (
                    "scholarship_currency",
                    models.CharField(
                        blank=True,
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_currency",
                                message="Currency must be a three-letter ISO 4217 code, e.g. AUD.",
                                regex="^[A-Z]{3}$",
                            )
                        ],
                    ),
                ),
                ("scholarship_notes", models.TextField(blank=True)),
                ("deposit_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                (
                    "deposit_currency",
                    models.CharField(
                        blank=True,
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_currency",
                                message="Currency must be a three-letter ISO 4217 code, e.g. AUD.",
                                regex="^[A-Z]{3}$",
                            )
                        ],
                    ),
                ),
                ("deposit_due_date", models.DateField(blank=True, null=True)),
                ("deposit_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                            ("deferred", "Deferred"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.TextField(blank=True)),
                (
                    "deferred_to_intake",
                    models.CharField(
                        blank=True,
                        help_text="Set only when the decision was to defer. The intake the offer was moved to.",
                        max_length=100,
                    ),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offers",
                        to="institutions.campus",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offers_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offers",
                        to="institutions.institution",
                    ),
                ),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offers",
                        to="applicant_journeys.applicantjourney",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offers",
                        to="institutions.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer",
                "verbose_name_plural": "Offers",
                "db_table": "offers_offer",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OfferCondition",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("academic_result", "Final Academic Results"),
                            ("english_test", "English Test Results"),
                            ("document_submission", "Document Submission"),
                            ("deposit_payment", "Deposit Payment"),
                            ("interview", "Interview or Verification"),
                            ("identity_confirmation", "Passport or Identity Confirmation"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(help_text="The requirement in the institution's own words.")),
                ("due_date", models.DateField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("satisfied", "Satisfied"),
                            ("waived", "Waived"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("resolution_note", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="conditions", to="offers.offer"
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offer_conditions_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer Condition",
                "verbose_name_plural": "Offer Conditions",
                "db_table": "offers_offercondition",
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(fields=["journey", "-created_at"], name="offer_journey_recent_idx"),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(fields=["status", "-created_at"], name="offer_status_recent_idx"),
        ),
        migrations.AddIndex(
            model_name="offercondition",
            index=models.Index(fields=["offer", "status"], name="condition_offer_status_idx"),
        ),
    ]
