# Generated by Django 5.2.17 on 2026-08-17 08:20
#
# offer_decided_at_idx supports the dashboard decision windows (§20):
# offers.selectors.get_decision_counts filters decided_at__isnull=False plus a
# date range on every pipeline/outcomes/conversion section render. Additive
# and reversible; no data impact (2026-08-17 security audit, P4).

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicant_journeys", "0002_target_country_ref"),
        ("institutions", "0003_trigram_search_indexes"),
        ("offers", "0002_english_only_names"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(fields=["decided_at"], name="offer_decided_at_idx"),
        ),
    ]
