# Generated by Django 5.1.9 on 2026-07-24 09:51

import uuid

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("applicants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "standalone_purpose",
                    models.TextField(
                        blank=True,
                        help_text="Why a document with no applicant exists, and who commissioned it. Required exactly when applicant is empty.",
                    ),
                ),
                (
                    "family",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("woda", "WODA"),
                            ("lor", "Letter of Recommendation"),
                            ("moi", "Medium of Instruction"),
                            ("bank_statement", "Bank Statement"),
                            ("bank_certificate", "Bank Certificate"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "template_key",
                    models.CharField(
                        db_index=True,
                        help_text="The template slug the frontend renders with, e.g. 'bank-vyas-statement'.",
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_template_key",
                                message="Template key must be a lowercase ASCII slug: letters and digits in hyphen-separated segments, e.g. 'bank-vyas-statement'.",
                                regex="^[a-z0-9]+(?:-[a-z0-9]+)*$",
                            )
                        ],
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='What staff call this document, e.g. "Vyas Statement".', max_length=255
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The entered source data, stored verbatim. The backend never computes, injects, or strips derived presentation values — see docs/DATA_CONTRACT.md.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("ready", "Ready"), ("archived", "Archived")],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("archive_reason", models.TextField(blank=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="applicants.applicant",
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_archived",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "documents_document",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["applicant", "-updated_at"], name="document_applicant_recent_idx"),
                    models.Index(fields=["status", "-updated_at"], name="document_status_recent_idx"),
                    models.Index(fields=["family", "-updated_at"], name="document_family_recent_idx"),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["label"], name="document_label_trgm_idx", opclasses=["gin_trgm_ops"]
                    ),
                ],
            },
        ),
    ]
