# Generated by Django 5.1.9
#
# Initial schema for document_history: two new tables, no change to any existing
# one. Fully reversible — rolling back drops both tables and nothing else.
#
# Composite indexes and the constraint, and the query each supports (§20):
#
# * ``snapshot_document_version_idx`` (document, -version_number) — the version
#   chain read (GET /documents/<id>/snapshots/) and the next-version lookup in
#   ``services.create_snapshot``.
# * ``document_snapshot_version_unique`` (document, version_number) — the
#   backstop under the row lock that allocates version numbers. Two concurrent
#   captures are serialized by ``select_for_update`` on the parent Document;
#   this constraint is what turns a failure of that mechanism into an error
#   rather than a duplicated version.
# * ``print_event_doc_recent_idx`` (document, -created_at) — the Document
#   History Timeline (GET /documents/<id>/timeline/), served off the
#   denormalized ``document`` column rather than a join through the snapshot.
#
# PrintEvent orders by ("-created_at", "-id"). The ``id`` tiebreaker is load
# bearing: ``created_at`` is not unique, the timeline is paginated, and a
# non-unique sort key lets a row appear on two pages or on none.


import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version_number",
                    models.PositiveIntegerField(help_text="Position in this document's version chain, 1-based."),
                ),
                ("family", models.CharField(max_length=20)),
                ("template_key", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=255)),
                (
                    "content",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Verbatim copy of the document body at capture time. Read from the document by the backend, never accepted from the client.",
                    ),
                ),
                (
                    "render_context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Client-supplied render-time context: the frontend-computed values, template version, and signatory metadata as they stood at capture. Stored verbatim, shape unvalidated.",
                    ),
                ),
                ("capture_note", models.TextField(blank=True)),
                (
                    "captured_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_snapshots_captured",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="snapshots", to="documents.document"
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Snapshot",
                "verbose_name_plural": "Document Snapshots",
                "db_table": "document_history_documentsnapshot",
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="PrintEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[("capture", "Capture"), ("reprint", "Reprint"), ("recovery", "Recovery")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="print_events",
                        to="documents.document",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_print_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="print_events",
                        to="document_history.documentsnapshot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Print Event",
                "verbose_name_plural": "Print Events",
                "db_table": "document_history_printevent",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="documentsnapshot",
            index=models.Index(fields=["document", "-version_number"], name="snapshot_document_version_idx"),
        ),
        migrations.AddConstraint(
            model_name="documentsnapshot",
            constraint=models.UniqueConstraint(
                fields=("document", "version_number"), name="document_snapshot_version_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="printevent",
            index=models.Index(fields=["document", "-created_at"], name="print_event_doc_recent_idx"),
        ),
    ]
