# Generated by Django 5.1.9 on 2026-08-16 18:39
#
# Indexes (§20 — each documented against the query it supports):
#   reminder_applicant_idx (applicant, -created_at) — the applicant detail
#       screen's reminders panel (list filtered to one applicant, newest first).
#   reminder_client_idx (client, -created_at) — the client detail screen's
#       reminders panel.
#   reminder_sweep_idx (status, due_date) — the nightly notification sweep's
#       due query (status=active, due_date<=today) and the list endpoint's
#       status + due-window filters.
#
# Constraints:
#   reminder_single_owner — exactly one of applicant/client is set (the
#       uploaded_files owner pattern; explicit disjunction so it evaluates the
#       same on PostgreSQL and the SQLite test suite).
#   reminder_closure_matches_status — active ⇒ closed_at is null; terminal
#       (completed/dismissed) ⇒ closed_at is set.
#
# Reversible: initial migration, plain CreateModel; reverse is dropping the
# table. No data migration needed.

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("applicants", "0005_trigram_search_indexes"),
        ("clients", "0002_english_only_names"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("due_date", models.DateField()),
                ("note", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Completed"), ("dismissed", "Dismissed")],
                        db_index=True,
                        default="active",
                        max_length=15,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminders",
                        to="applicants.applicant",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminders",
                        to="clients.client",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminders_closed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reminders_reminder",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["applicant", "-created_at"], name="reminder_applicant_idx"),
                    models.Index(fields=["client", "-created_at"], name="reminder_client_idx"),
                    models.Index(fields=["status", "due_date"], name="reminder_sweep_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("applicant__isnull", False), ("client__isnull", True)),
                            models.Q(("applicant__isnull", True), ("client__isnull", False)),
                            _connector="OR",
                        ),
                        name="reminder_single_owner",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("closed_at__isnull", True), ("status", "active")),
                            models.Q(("closed_at__isnull", False), ("status__in", ["completed", "dismissed"])),
                            _connector="OR",
                        ),
                        name="reminder_closure_matches_status",
                    ),
                ],
            },
        ),
    ]
