# Generated by Django 5.1.9 on 2026-07-23 09:20

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadSource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_code",
                                message="Code must be ASCII: lowercase letters, digits, and _ - only, starting and ending with a letter or digit.",
                                regex="^[a-z0-9](?:[a-z0-9_-]{0,48}[a-z0-9])?$",
                            )
                        ],
                    ),
                ),
                ("name_np", models.CharField(max_length=150)),
                ("name_en", models.CharField(blank=True, max_length=150)),
                ("name_romanized", models.CharField(blank=True, max_length=150)),
                (
                    "requires_detail",
                    models.BooleanField(
                        default=False,
                        help_text='Set on catch-all entries such as "Other" so the user must explain their choice.',
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Lead Source",
                "verbose_name_plural": "Lead Sources",
                "db_table": "leads_leadsource",
                "ordering": ["display_order", "name_np"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LossReason",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_code",
                                message="Code must be ASCII: lowercase letters, digits, and _ - only, starting and ending with a letter or digit.",
                                regex="^[a-z0-9](?:[a-z0-9_-]{0,48}[a-z0-9])?$",
                            )
                        ],
                    ),
                ),
                ("name_np", models.CharField(max_length=150)),
                ("name_en", models.CharField(blank=True, max_length=150)),
                ("name_romanized", models.CharField(blank=True, max_length=150)),
                (
                    "requires_detail",
                    models.BooleanField(
                        default=False,
                        help_text='Set on catch-all entries such as "Other" so the user must explain their choice.',
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Loss Reason",
                "verbose_name_plural": "Loss Reasons",
                "db_table": "leads_lossreason",
                "ordering": ["display_order", "name_np"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name_np", models.CharField(max_length=255)),
                ("full_name_en", models.CharField(blank=True, max_length=255)),
                ("full_name_romanized", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "source_detail",
                    models.CharField(
                        blank=True,
                        help_text='Required when the chosen source requires detail (e.g. "Other").',
                        max_length=255,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contact_attempted", "Contact Attempted"),
                            ("contacted", "Contacted"),
                            ("counselling", "Counselling"),
                            ("follow_up", "Follow-up"),
                            ("ready_for_conversion", "Ready for Conversion"),
                            ("converted", "Converted"),
                            ("lost", "Lost"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=30,
                    ),
                ),
                ("last_followed_up_at", models.DateTimeField(blank=True, null=True)),
                ("lost_detail", models.TextField(blank=True)),
                ("lost_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stage_before_loss",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "New"),
                            ("contact_attempted", "Contact Attempted"),
                            ("contacted", "Contacted"),
                            ("counselling", "Counselling"),
                            ("follow_up", "Follow-up"),
                            ("ready_for_conversion", "Ready for Conversion"),
                            ("converted", "Converted"),
                            ("lost", "Lost"),
                        ],
                        max_length=30,
                    ),
                ),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "converted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads_converted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The Lead Manager who created this lead. Immutable — ownership never moves.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_followed_up_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_followups_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lost_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads_marked_lost",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="leads", to="leads.leadsource"
                    ),
                ),
                (
                    "lost_reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads",
                        to="leads.lossreason",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "db_table": "leads_lead",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadNote",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lead_notes_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="notes", to="leads.lead"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Note",
                "verbose_name_plural": "Lead Notes",
                "db_table": "leads_leadnote",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadStudyInterest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interested_countries",
                    models.JSONField(
                        blank=True, default=list, help_text="List of country names the person is considering."
                    ),
                ),
                (
                    "study_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("school", "School"),
                            ("certificate", "Certificate"),
                            ("diploma", "Diploma"),
                            ("bachelors", "Bachelor's"),
                            ("postgraduate_diploma", "Postgraduate Diploma"),
                            ("masters", "Master's"),
                            ("phd", "PhD"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("field_of_study", models.CharField(blank=True, max_length=150)),
                (
                    "preferred_intake",
                    models.CharField(
                        blank=True, help_text='Free text at this stage, e.g. "Fall 2026".', max_length=50
                    ),
                ),
                ("budget_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("budget_currency", models.CharField(blank=True, help_text="ISO 4217 code, e.g. NPR.", max_length=3)),
                ("scholarship_interest", models.BooleanField(default=False)),
                ("highest_qualification", models.CharField(blank=True, max_length=150)),
                (
                    "language_test_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("not_taken", "Not Taken"),
                            ("preparing", "Preparing"),
                            ("booked", "Booked"),
                            ("taken", "Taken"),
                            ("not_required", "Not Required"),
                        ],
                        max_length=20,
                    ),
                ),
                ("interest_notes", models.TextField(blank=True)),
                (
                    "lead",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="study_interest", to="leads.lead"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Study Interest",
                "verbose_name_plural": "Lead Study Interests",
                "db_table": "leads_leadstudyinterest",
            },
        ),
        migrations.CreateModel(
            name="LeadContactNumber",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_contact_number",
                                message="Contact number may contain digits, spaces, and + - ( ) only.",
                                regex="^\\+?[0-9][0-9 ()\\-]{4,31}$",
                            )
                        ],
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("home", "Home"),
                            ("work", "Work"),
                            ("whatsapp", "WhatsApp"),
                            ("viber", "Viber"),
                            ("other", "Other"),
                        ],
                        default="mobile",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="contact_numbers", to="leads.lead"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Contact Number",
                "verbose_name_plural": "Lead Contact Numbers",
                "db_table": "leads_leadcontactnumber",
                "ordering": ["-is_primary", "created_at"],
                "constraints": [models.UniqueConstraint(fields=("lead", "number"), name="uniq_lead_contact_number")],
            },
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["created_by", "-created_at"], name="lead_owner_recent_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["stage", "-created_at"], name="lead_stage_recent_idx"),
        ),
    ]
