# Generated by Django 5.1.9 on 2026-07-23 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicant_journeys", "0001_initial"),
        ("applicants", "0001_initial"),
        ("leads", "0002_pg_trgm_lead_name_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="converted_applicant",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="originating_lead",
                to="applicants.applicant",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="converted_journey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="originating_leads",
                to="applicant_journeys.applicantjourney",
            ),
        ),
    ]
