"""
Management command: reset_dev_data

Dev-only: deletes all data fed into the database during development EXCEPT
the Core Policy Engine registry (core.policy_engine), which the platform
needs to run at all and is regenerable from registry.py anyway (see
sync_policy_registry) — not what this command is for.

Preserved (never touched):
- Every model under the policy_engine app label.
- Django's own framework-managed tables that just get regenerated by Django
  itself (contenttypes.ContentType, auth.Permission, auth.Group).
- Any model whose QuerySet overrides delete() to block bulk deletion —
  detected generically (type(model.objects.all()).delete is not
  django.db.models.QuerySet.delete), not by a hardcoded per-app list. Several
  apps independently implement this same append-only audit-log pattern
  (authenticate.AuthEvent, organization.OrganizationEventLog, every
  policy_engine append-only model) and each would raise its own app-specific
  ImmutabilityError if a bulk delete were attempted — this command treats
  that as an authoritative "do not touch" signal from the model itself, so it
  never needs updating when a new app adds its own append-only log.

Cleared: everything else — authenticate (including the superadmin User row),
organization, permissions, and per-session/per-user dev artifacts (axes
lockout tracking, django_otp devices, Django sessions, admin log entries).
axes.AccessAttempt/AccessLog/AccessFailureLog have no FK to User (tracked by
username/IP string), so they would not be cleaned up by cascading from User
deletion and must be cleared explicitly.

Deletion order does not matter: there are no on_delete=PROTECT relationships
anywhere outside policy_engine, so Model.objects.all().delete() on each
targeted model, in any order, is safe (cascades and double-deletes of
already-empty querysets are no-ops).

Refuses to run unless ENVIRONMENT=development (or unset, which defaults to
development) — the same check core/settings/__init__.py uses to select the
settings module.

Usage:
    python manage.py reset_dev_data --dry-run
    python manage.py reset_dev_data --force
"""

import os

from django.apps import apps
from django.core.management.base import BaseCommand, CommandError
from django.db.models import QuerySet

PRESERVED_APP_LABELS = {"policy_engine"}
PRESERVED_MODELS = {
    ("contenttypes", "ContentType"),
    ("auth", "Permission"),
    ("auth", "Group"),
}


def _is_append_only(model) -> bool:
    """True if this model's QuerySet overrides delete() to block bulk deletion."""
    return type(model.objects.all()).delete is not QuerySet.delete


class Command(BaseCommand):
    help = (
        "Dev-only: delete all data except Core Policy Engine metadata, to clear hoax/test data fed during development."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--dry-run",
            action="store_true",
            default=False,
            help="Preview row counts that would be deleted without writing anything.",
        )
        parser.add_argument(
            "--force",
            action="store_true",
            default=False,
            help="Actually perform the deletion. Required unless --dry-run is passed.",
        )

    def handle(self, *args, **options):
        environment = os.environ.get("ENVIRONMENT", "development")
        if environment != "development":
            raise CommandError(
                f"Refusing to run: ENVIRONMENT={environment!r}. "
                "reset_dev_data only runs when ENVIRONMENT=development."
            )

        dry_run = options["dry_run"]
        force = options["force"]
        if not dry_run and not force:
            raise CommandError("Pass --dry-run to actually delete.")

        deletable, append_only = self._partition_target_models()
        counts = {model: model.objects.count() for model in deletable}
        total = sum(counts.values())

        action = "Would delete" if dry_run else "Deleting"
        self.stdout.write(f"[DRY RUN] {action}:" if dry_run else f"{action}:")
        for model, count in counts.items():
            if count:
                self.stdout.write(f"  {model._meta.app_label}.{model.__name__}: {count}")
        if append_only:
            self.stdout.write("Preserved (append-only, never touched regardless of --force):")
            for model in append_only:
                self.stdout.write(f"  {model._meta.app_label}.{model.__name__}")
        self.stdout.write(self.style.WARNING("Policy Engine data untouched."))

        if dry_run:
            return

        for model in deletable:
            model.objects.all().delete()

        self.stdout.write(self.style.SUCCESS(f"Deleted {total} row(s) across {len(deletable)} model(s)."))
        self.stdout.write(
            self.style.WARNING(
                "authenticate.User was cleared, including the superadmin account. "
                "Run `python manage.py bootstrap_superadmin` to restore platform access."
            )
        )

    def _partition_target_models(self) -> tuple[list, list]:
        deletable = []
        append_only = []
        for app_config in apps.get_app_configs():
            if app_config.label in PRESERVED_APP_LABELS:
                continue
            for model in app_config.get_models():
                if (app_config.label, model.__name__) in PRESERVED_MODELS:
                    continue
                if _is_append_only(model):
                    append_only.append(model)
                else:
                    deletable.append(model)
        return deletable, append_only
