# Generated by Django 5.1.9 on 2026-07-24 11:23
#
# Initial schema for document_templates: two new tables, no change to any
# existing one. Fully reversible — rolling back drops both tables and nothing
# else. No foreign key into `documents`: this app imports that app's family
# enum and key-validation rule in Python, but holds no database relation to it,
# which is why the catalogue is advisory rather than enforcing.
#
# Indexes and the constraint, and the query each supports (§20):
#
# * `key` UNIQUE — the catalogue's identity. Every document stores this slug as
#   a plain string, so two rows claiming it would make "which template is this
#   document using" unanswerable.
# * `signatory_status_name_idx` (status, name_np) — the frontend's only call
#   into this app: the active-signatory picker, alphabetical.
# * `signatory_name_{np,en,rom}_trgm_idx` — GIN trigram over the three name
#   forms, so a Roman-script query finds a Devanagari-primary record (§39.6).
# * `template_family_status_idx` (family, status) — "every active bank
#   statement template", the shape of the picker the frontend draws.
#
# The `leads` dependency below is not a data relation — it is the migration
# that creates the `pg_trgm` extension the three GIN indexes require. Declared
# explicitly rather than left to inter-app migration ordering, which is what
# `applicants` relies on for the same indexes.

import uuid

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("leads", "0002_pg_trgm_lead_name_search"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "status_note",
                    models.TextField(
                        blank=True,
                        help_text="Why this entry is in its current state. Optional — no transition here requires one.",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="The template slug the frontend renders with, e.g. 'bank-vyas-statement'.",
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_template_key",
                                message="Template key must be a lowercase ASCII slug: letters and digits in hyphen-separated segments, e.g. 'bank-vyas-statement'.",
                                regex="^[a-z0-9]+(?:-[a-z0-9]+)*$",
                            )
                        ],
                    ),
                ),
                (
                    "family",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("woda", "WODA"),
                            ("lor", "Letter of Recommendation"),
                            ("moi", "Medium of Instruction"),
                            ("bank_statement", "Bank Statement"),
                            ("bank_certificate", "Bank Certificate"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='What staff call this template in the picker, e.g. "Vyas Statement".', max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_templates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Template",
                "verbose_name_plural": "Document Templates",
                "db_table": "document_templates_documenttemplate",
                "ordering": ["family", "display_order", "label"],
                "indexes": [models.Index(fields=["family", "status"], name="template_family_status_idx")],
            },
        ),
        migrations.CreateModel(
            name="Signatory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "status_note",
                    models.TextField(
                        blank=True,
                        help_text="Why this entry is in its current state. Optional — no transition here requires one.",
                    ),
                ),
                ("name_np", models.CharField(max_length=255)),
                ("name_en", models.CharField(blank=True, max_length=255)),
                (
                    "name_romanized",
                    models.CharField(
                        blank=True,
                        help_text="Auto-derived from name_np by the service layer (§39.3). Never hand-entered.",
                        max_length=255,
                    ),
                ),
                ("title_np", models.CharField(blank=True, max_length=255)),
                ("title_en", models.CharField(blank=True, max_length=255)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text='Free text, e.g. "director", "instructor". Not an enum — see docs/DATA_CONTRACT.md.',
                        max_length=100,
                    ),
                ),
                (
                    "signature_image_url",
                    models.URLField(
                        blank=True,
                        help_text="A link to a signature image hosted elsewhere. Not an upload — see docs/DATA_CONTRACT.md.",
                        max_length=500,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signatories_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Signatory",
                "verbose_name_plural": "Signatories",
                "db_table": "document_templates_signatory",
                "ordering": ["name_np"],
                "indexes": [
                    models.Index(fields=["status", "name_np"], name="signatory_status_name_idx"),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["name_np"], name="signatory_name_np_trgm_idx", opclasses=["gin_trgm_ops"]
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["name_en"], name="signatory_name_en_trgm_idx", opclasses=["gin_trgm_ops"]
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["name_romanized"], name="signatory_name_rom_trgm_idx", opclasses=["gin_trgm_ops"]
                    ),
                ],
            },
        ),
    ]
