# Generated by Django 5.1.9 on 2026-07-22 14:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("superadmin", "Superadmin"),
                            ("admin", "Admin"),
                            ("lead_manager", "Lead Manager"),
                            ("system", "System"),
                            ("ai", "AI"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("actor_label", models.CharField(blank=True, max_length=150)),
                ("app_label", models.CharField(db_index=True, max_length=100)),
                ("action", models.CharField(db_index=True, max_length=100)),
                ("entity_type", models.CharField(blank=True, max_length=100)),
                ("entity_id", models.UUIDField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Audit Event",
                "verbose_name_plural": "Audit Events",
                "db_table": "audit_auditevent",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["entity_type", "entity_id"], name="audit_audit_entity__0bff9a_idx")],
            },
        ),
    ]
