# Generated by Django 5.1.9 on 2026-07-24 12:12
#
# Initial schema for uploaded_files: one new table, no change to any existing
# one. Fully reversible — rolling back drops the table and nothing else.
#
# Five PROTECT foreign keys point OUT of this table into applicants,
# applicant_journeys, offers, documents, and document_history. None of those
# apps gains a column here or anywhere else: no shipped app references this
# model, deliberately, so this migration cannot break any existing row or any
# existing query. Rolling it back is safe as long as the volume behind
# MEDIA_ROOT is retained — the table is dropped, the bytes are not, and nothing
# in this project deletes a file.
#
# Data impact: none. The table starts empty; there is no data migration and no
# backfill, because before this migration there was nowhere in Grandway for a
# file to exist.
#
# The constraint and the indexes, and what each one is for (§20):
#
# * `uploaded_file_single_owner` — CHECK: exactly one of the five owner columns
#   is non-null. Written as a five-way OR of explicit null-patterns rather than
#   an arithmetic null-count so it evaluates identically on PostgreSQL and on
#   the SQLite the test suite runs against. This is the rule that makes
#   "whose file is this" always answerable, enforced below the application so
#   the admin, the shell, and any future management command are bound by it too.
# * `replaces` UNIQUE (via OneToOne) — keeps the replacement chain from
#   forking, so "which file is current" always has exactly one answer.
# * `file_applicant_recent_idx`, `file_journey_recent_idx`,
#   `file_offer_recent_idx`, `file_document_recent_idx` — the four per-record
#   file panels: "this record's files, newest first".
# * `file_review_queue_idx` (verification_status, -created_at) — the review
#   queue, `?verification_status=pending`.
# * `file_category_recent_idx` (category, -created_at) — the category filter on
#   the file list.
# * `file_orig_name_trgm_idx` — GIN trigram over `original_filename` for
#   `?search=` (§39.6). One field rather than the three-form set the other apps
#   index, because a filename has no Devanagari/Roman/romanized triple.
# * `checksum_sha256` — plain B-tree, for duplicate discovery. Duplicates are
#   recorded, never blocked.
#
# The `leads` dependency below is not a data relation — it is the migration that
# creates the `pg_trgm` extension the GIN index requires. Declared explicitly
# rather than left to inter-app migration ordering, matching the call
# `document_templates` made.

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import uploaded_files.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("applicant_journeys", "0001_initial"),
        ("applicants", "0001_initial"),
        ("document_history", "0001_initial"),
        ("documents", "0001_initial"),
        # Not a data relation — this is the migration that creates the pg_trgm
        # extension `file_orig_name_trgm_idx` is built on.
        ("leads", "0002_pg_trgm_lead_name_search"),
        ("offers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("passport", "Passport"),
                            ("photograph", "Photograph"),
                            ("academic_transcript", "Academic Transcript"),
                            ("academic_certificate", "Academic Certificate"),
                            ("test_score_report", "Test Score Report"),
                            ("offer_letter", "Offer Letter"),
                            ("financial", "Financial Document"),
                            ("sponsorship", "Sponsorship Document"),
                            ("signature_image", "Signature Image"),
                            ("generated_document", "Generated Document"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "upload_source",
                    models.CharField(
                        choices=[("staff_upload", "Staff Upload"), ("system_generated", "System Generated")],
                        default="staff_upload",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("file", models.FileField(max_length=500, upload_to=uploaded_files.models.upload_destination)),
                (
                    "original_filename",
                    models.CharField(
                        help_text="The name the file arrived with. Never used as the name on disk.", max_length=255
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        help_text="Derived from the validated extension — never the client's declared Content-Type.",
                        max_length=100,
                    ),
                ),
                ("size_bytes", models.PositiveBigIntegerField()),
                (
                    "checksum_sha256",
                    models.CharField(
                        db_index=True,
                        help_text="Streamed SHA-256 hex digest, computed once at upload. Duplicates are recorded, not blocked.",
                        max_length=64,
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        default=1, help_text="Position in this file's replacement chain, 1-based."
                    ),
                ),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("verified", "Verified"), ("rejected", "Rejected")],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("archive_reason", models.TextField(blank=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_files",
                        to="applicants.applicant",
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files_archived",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_files",
                        to="documents.document",
                    ),
                ),
                (
                    "journey",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_files",
                        to="applicant_journeys.applicantjourney",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_files",
                        to="offers.offer",
                    ),
                ),
                (
                    "replaces",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replaced_by",
                        to="uploaded_files.uploadedfile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_files",
                        to="document_history.documentsnapshot",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files_superseded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="files_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Uploaded File",
                "verbose_name_plural": "Uploaded Files",
                "db_table": "uploaded_files_uploadedfile",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["applicant", "-created_at"], name="file_applicant_recent_idx"),
                    models.Index(fields=["journey", "-created_at"], name="file_journey_recent_idx"),
                    models.Index(fields=["offer", "-created_at"], name="file_offer_recent_idx"),
                    models.Index(fields=["document", "-created_at"], name="file_document_recent_idx"),
                    models.Index(fields=["verification_status", "-created_at"], name="file_review_queue_idx"),
                    models.Index(fields=["category", "-created_at"], name="file_category_recent_idx"),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["original_filename"], name="file_orig_name_trgm_idx", opclasses=["gin_trgm_ops"]
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("applicant__isnull", False),
                                ("document__isnull", True),
                                ("journey__isnull", True),
                                ("offer__isnull", True),
                                ("snapshot__isnull", True),
                            ),
                            models.Q(
                                ("applicant__isnull", True),
                                ("document__isnull", True),
                                ("journey__isnull", False),
                                ("offer__isnull", True),
                                ("snapshot__isnull", True),
                            ),
                            models.Q(
                                ("applicant__isnull", True),
                                ("document__isnull", True),
                                ("journey__isnull", True),
                                ("offer__isnull", False),
                                ("snapshot__isnull", True),
                            ),
                            models.Q(
                                ("applicant__isnull", True),
                                ("document__isnull", False),
                                ("journey__isnull", True),
                                ("offer__isnull", True),
                                ("snapshot__isnull", True),
                            ),
                            models.Q(
                                ("applicant__isnull", True),
                                ("document__isnull", True),
                                ("journey__isnull", True),
                                ("offer__isnull", True),
                                ("snapshot__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="uploaded_file_single_owner",
                    )
                ],
            },
        ),
    ]
